// 조수사 (Japanese counters) content. Each counter lists what it counts (useKo)
// plus the 1-10 forms with CORRECT irregular readings baked in as furigana
// tokens ({ b, r? }). Irregulars are hand-authored, not generated: 一つ ひとつ,
// 一人 ひとり, 二人 ふたり, 一匹 いっぴき / 三匹 さんびき / 六匹 ろっぴき,
// 一本 いっぽん / 三本 さんぼん / 六本 ろっぽん, 一杯 いっぱい / 三杯 さんばい,
// 一階 いっかい / 三階 さんがい(or さんかい) / 六階 ろっかい, 三百 etc.
// Static data, no network. tokens render through FuriganaTokens; readingJa is
// the full kana reading (for TTS via expo-speech ja-JP and for screen readers).
export type CounterForm = {
  n: number; // 1-10
  readingJa: string; // full kana reading, e.g. "いっぴき"
  tokens: { b: string; r?: string }[]; // furigana-annotated surface form
};

export type Counter = {
  id: string;
  counter: string; // the counter surface, e.g. "匹"
  reading: string; // base reading of the counter kana, e.g. "ひき"
  useKo: string; // 뭘 셀 때 쓰는지 (Korean)
  exampleKo: string; // a short usage note in Korean
  hardKo?: string; // Korean note about the tricky/irregular readings
  forms: CounterForm[]; // 1..10
};

// helper readability note: r is the reading placed above the b (base) glyphs.
// Numerals keep their own reading token so learners see the full mora count.

export const COUNTERS: Counter[] = [
  {
    id: 'tsu',
    counter: 'つ',
    reading: 'つ',
    useKo: '작은 물건 · 나이(어린) · 뭐든 애매할 때 (범용)',
    exampleKo: '사과를 하나 = りんごを一つ. 10까지만 쓰고 11부터는 十一(じゅういち)로 세요.',
    hardKo: '전부 불규칙. 一つ(ひとつ)~九つ(ここのつ)까지 고유어 수사, 十(とお)는 つ가 안 붙어요.',
    forms: [
      { n: 1, readingJa: 'ひとつ', tokens: [{ b: '一', r: 'ひと' }, { b: 'つ' }] },
      { n: 2, readingJa: 'ふたつ', tokens: [{ b: '二', r: 'ふた' }, { b: 'つ' }] },
      { n: 3, readingJa: 'みっつ', tokens: [{ b: '三', r: 'みっ' }, { b: 'つ' }] },
      { n: 4, readingJa: 'よっつ', tokens: [{ b: '四', r: 'よっ' }, { b: 'つ' }] },
      { n: 5, readingJa: 'いつつ', tokens: [{ b: '五', r: 'いつ' }, { b: 'つ' }] },
      { n: 6, readingJa: 'むっつ', tokens: [{ b: '六', r: 'むっ' }, { b: 'つ' }] },
      { n: 7, readingJa: 'ななつ', tokens: [{ b: '七', r: 'なな' }, { b: 'つ' }] },
      { n: 8, readingJa: 'やっつ', tokens: [{ b: '八', r: 'やっ' }, { b: 'つ' }] },
      { n: 9, readingJa: 'ここのつ', tokens: [{ b: '九', r: 'ここの' }, { b: 'つ' }] },
      { n: 10, readingJa: 'とお', tokens: [{ b: '十', r: 'とお' }] },
    ],
  },
  {
    id: 'ko',
    counter: '個',
    reading: 'こ',
    useKo: '작고 둥근 물건 전반 (사과 · 계란 · 돌 · 부품 등)',
    exampleKo: 'たまごを三個(さんこ)ください = 계란 세 개 주세요.',
    hardKo: '1(いっこ) · 6(ろっこ) · 8(はっこ) · 10(じゅっこ/じっこ)에서 촉음(っ)이 생겨요.',
    forms: [
      { n: 1, readingJa: 'いっこ', tokens: [{ b: '一', r: 'いっ' }, { b: '個', r: 'こ' }] },
      { n: 2, readingJa: 'にこ', tokens: [{ b: '二', r: 'に' }, { b: '個', r: 'こ' }] },
      { n: 3, readingJa: 'さんこ', tokens: [{ b: '三', r: 'さん' }, { b: '個', r: 'こ' }] },
      { n: 4, readingJa: 'よんこ', tokens: [{ b: '四', r: 'よん' }, { b: '個', r: 'こ' }] },
      { n: 5, readingJa: 'ごこ', tokens: [{ b: '五', r: 'ご' }, { b: '個', r: 'こ' }] },
      { n: 6, readingJa: 'ろっこ', tokens: [{ b: '六', r: 'ろっ' }, { b: '個', r: 'こ' }] },
      { n: 7, readingJa: 'ななこ', tokens: [{ b: '七', r: 'なな' }, { b: '個', r: 'こ' }] },
      { n: 8, readingJa: 'はっこ', tokens: [{ b: '八', r: 'はっ' }, { b: '個', r: 'こ' }] },
      { n: 9, readingJa: 'きゅうこ', tokens: [{ b: '九', r: 'きゅう' }, { b: '個', r: 'こ' }] },
      { n: 10, readingJa: 'じゅっこ', tokens: [{ b: '十', r: 'じゅっ' }, { b: '個', r: 'こ' }] },
    ],
  },
  {
    id: 'nin',
    counter: '人',
    reading: 'にん',
    useKo: '사람을 셀 때',
    exampleKo: '家族(かぞく)は四人(よにん)です = 우리 가족은 네 명이에요.',
    hardKo: '1(ひとり) · 2(ふたり)만 고유어로 완전히 달라요. 4는 よにん(×よんにん).',
    forms: [
      { n: 1, readingJa: 'ひとり', tokens: [{ b: '一', r: 'ひと' }, { b: '人', r: 'り' }] },
      { n: 2, readingJa: 'ふたり', tokens: [{ b: '二', r: 'ふた' }, { b: '人', r: 'り' }] },
      { n: 3, readingJa: 'さんにん', tokens: [{ b: '三', r: 'さん' }, { b: '人', r: 'にん' }] },
      { n: 4, readingJa: 'よにん', tokens: [{ b: '四', r: 'よ' }, { b: '人', r: 'にん' }] },
      { n: 5, readingJa: 'ごにん', tokens: [{ b: '五', r: 'ご' }, { b: '人', r: 'にん' }] },
      { n: 6, readingJa: 'ろくにん', tokens: [{ b: '六', r: 'ろく' }, { b: '人', r: 'にん' }] },
      { n: 7, readingJa: 'しちにん', tokens: [{ b: '七', r: 'しち' }, { b: '人', r: 'にん' }] },
      { n: 8, readingJa: 'はちにん', tokens: [{ b: '八', r: 'はち' }, { b: '人', r: 'にん' }] },
      { n: 9, readingJa: 'きゅうにん', tokens: [{ b: '九', r: 'きゅう' }, { b: '人', r: 'にん' }] },
      { n: 10, readingJa: 'じゅうにん', tokens: [{ b: '十', r: 'じゅう' }, { b: '人', r: 'にん' }] },
    ],
  },
  {
    id: 'hiki',
    counter: '匹',
    reading: 'ひき',
    useKo: '작은 동물 (개 · 고양이 · 물고기 · 벌레 등)',
    exampleKo: '猫(ねこ)が三匹(さんびき)いる = 고양이가 세 마리 있어.',
    hardKo: 'ひ가 소리에 따라 ぴ/び로 바뀌어요. 1いっぴき 3さんびき 6ろっぴき 8はっぴき 10じゅっぴき.',
    forms: [
      { n: 1, readingJa: 'いっぴき', tokens: [{ b: '一', r: 'いっ' }, { b: '匹', r: 'ぴき' }] },
      { n: 2, readingJa: 'にひき', tokens: [{ b: '二', r: 'に' }, { b: '匹', r: 'ひき' }] },
      { n: 3, readingJa: 'さんびき', tokens: [{ b: '三', r: 'さん' }, { b: '匹', r: 'びき' }] },
      { n: 4, readingJa: 'よんひき', tokens: [{ b: '四', r: 'よん' }, { b: '匹', r: 'ひき' }] },
      { n: 5, readingJa: 'ごひき', tokens: [{ b: '五', r: 'ご' }, { b: '匹', r: 'ひき' }] },
      { n: 6, readingJa: 'ろっぴき', tokens: [{ b: '六', r: 'ろっ' }, { b: '匹', r: 'ぴき' }] },
      { n: 7, readingJa: 'ななひき', tokens: [{ b: '七', r: 'なな' }, { b: '匹', r: 'ひき' }] },
      { n: 8, readingJa: 'はっぴき', tokens: [{ b: '八', r: 'はっ' }, { b: '匹', r: 'ぴき' }] },
      { n: 9, readingJa: 'きゅうひき', tokens: [{ b: '九', r: 'きゅう' }, { b: '匹', r: 'ひき' }] },
      { n: 10, readingJa: 'じゅっぴき', tokens: [{ b: '十', r: 'じゅっ' }, { b: '匹', r: 'ぴき' }] },
    ],
  },
  {
    id: 'hon',
    counter: '本',
    reading: 'ほん',
    useKo: '가늘고 긴 물건 (병 · 우산 · 연필 · 나무 · 전화통화 등)',
    exampleKo: 'ビールを二本(にほん) = 맥주 두 병.',
    hardKo: 'ほ가 ぽ/ぼ로 변해요. 1いっぽん 3さんぼん 6ろっぽん 8はっぽん 10じゅっぽん.',
    forms: [
      { n: 1, readingJa: 'いっぽん', tokens: [{ b: '一', r: 'いっ' }, { b: '本', r: 'ぽん' }] },
      { n: 2, readingJa: 'にほん', tokens: [{ b: '二', r: 'に' }, { b: '本', r: 'ほん' }] },
      { n: 3, readingJa: 'さんぼん', tokens: [{ b: '三', r: 'さん' }, { b: '本', r: 'ぼん' }] },
      { n: 4, readingJa: 'よんほん', tokens: [{ b: '四', r: 'よん' }, { b: '本', r: 'ほん' }] },
      { n: 5, readingJa: 'ごほん', tokens: [{ b: '五', r: 'ご' }, { b: '本', r: 'ほん' }] },
      { n: 6, readingJa: 'ろっぽん', tokens: [{ b: '六', r: 'ろっ' }, { b: '本', r: 'ぽん' }] },
      { n: 7, readingJa: 'ななほん', tokens: [{ b: '七', r: 'なな' }, { b: '本', r: 'ほん' }] },
      { n: 8, readingJa: 'はっぽん', tokens: [{ b: '八', r: 'はっ' }, { b: '本', r: 'ぽん' }] },
      { n: 9, readingJa: 'きゅうほん', tokens: [{ b: '九', r: 'きゅう' }, { b: '本', r: 'ほん' }] },
      { n: 10, readingJa: 'じゅっぽん', tokens: [{ b: '十', r: 'じゅっ' }, { b: '本', r: 'ぽん' }] },
    ],
  },
  {
    id: 'mai',
    counter: '枚',
    reading: 'まい',
    useKo: '얇고 평평한 물건 (종이 · 표 · 접시 · 셔츠 · CD 등)',
    exampleKo: '切符(きっぷ)を二枚(にまい) = 표 두 장.',
    hardKo: '음변화가 거의 없어서 초보에게 제일 쉬운 조수사예요.',
    forms: [
      { n: 1, readingJa: 'いちまい', tokens: [{ b: '一', r: 'いち' }, { b: '枚', r: 'まい' }] },
      { n: 2, readingJa: 'にまい', tokens: [{ b: '二', r: 'に' }, { b: '枚', r: 'まい' }] },
      { n: 3, readingJa: 'さんまい', tokens: [{ b: '三', r: 'さん' }, { b: '枚', r: 'まい' }] },
      { n: 4, readingJa: 'よんまい', tokens: [{ b: '四', r: 'よん' }, { b: '枚', r: 'まい' }] },
      { n: 5, readingJa: 'ごまい', tokens: [{ b: '五', r: 'ご' }, { b: '枚', r: 'まい' }] },
      { n: 6, readingJa: 'ろくまい', tokens: [{ b: '六', r: 'ろく' }, { b: '枚', r: 'まい' }] },
      { n: 7, readingJa: 'ななまい', tokens: [{ b: '七', r: 'なな' }, { b: '枚', r: 'まい' }] },
      { n: 8, readingJa: 'はちまい', tokens: [{ b: '八', r: 'はち' }, { b: '枚', r: 'まい' }] },
      { n: 9, readingJa: 'きゅうまい', tokens: [{ b: '九', r: 'きゅう' }, { b: '枚', r: 'まい' }] },
      { n: 10, readingJa: 'じゅうまい', tokens: [{ b: '十', r: 'じゅう' }, { b: '枚', r: 'まい' }] },
    ],
  },
  {
    id: 'satsu',
    counter: '冊',
    reading: 'さつ',
    useKo: '책 · 노트 · 잡지 등 제본된 것',
    exampleKo: '本(ほん)を三冊(さんさつ)買(か)った = 책을 세 권 샀어.',
    hardKo: '1(いっさつ) · 8(はっさつ) · 10(じゅっさつ)에서 촉음이 생겨요.',
    forms: [
      { n: 1, readingJa: 'いっさつ', tokens: [{ b: '一', r: 'いっ' }, { b: '冊', r: 'さつ' }] },
      { n: 2, readingJa: 'にさつ', tokens: [{ b: '二', r: 'に' }, { b: '冊', r: 'さつ' }] },
      { n: 3, readingJa: 'さんさつ', tokens: [{ b: '三', r: 'さん' }, { b: '冊', r: 'さつ' }] },
      { n: 4, readingJa: 'よんさつ', tokens: [{ b: '四', r: 'よん' }, { b: '冊', r: 'さつ' }] },
      { n: 5, readingJa: 'ごさつ', tokens: [{ b: '五', r: 'ご' }, { b: '冊', r: 'さつ' }] },
      { n: 6, readingJa: 'ろくさつ', tokens: [{ b: '六', r: 'ろく' }, { b: '冊', r: 'さつ' }] },
      { n: 7, readingJa: 'ななさつ', tokens: [{ b: '七', r: 'なな' }, { b: '冊', r: 'さつ' }] },
      { n: 8, readingJa: 'はっさつ', tokens: [{ b: '八', r: 'はっ' }, { b: '冊', r: 'さつ' }] },
      { n: 9, readingJa: 'きゅうさつ', tokens: [{ b: '九', r: 'きゅう' }, { b: '冊', r: 'さつ' }] },
      { n: 10, readingJa: 'じゅっさつ', tokens: [{ b: '十', r: 'じゅっ' }, { b: '冊', r: 'さつ' }] },
    ],
  },
  {
    id: 'hai',
    counter: '杯',
    reading: 'はい',
    useKo: '잔 · 그릇에 담은 음료 · 밥 (커피 · 물 · 라멘 등)',
    exampleKo: 'コーヒーを一杯(いっぱい) = 커피 한 잔.',
    hardKo: 'は가 ぱ/ば로 변해요. 1いっぱい 3さんばい 6ろっぱい 8はっぱい 10じゅっぱい.',
    forms: [
      { n: 1, readingJa: 'いっぱい', tokens: [{ b: '一', r: 'いっ' }, { b: '杯', r: 'ぱい' }] },
      { n: 2, readingJa: 'にはい', tokens: [{ b: '二', r: 'に' }, { b: '杯', r: 'はい' }] },
      { n: 3, readingJa: 'さんばい', tokens: [{ b: '三', r: 'さん' }, { b: '杯', r: 'ばい' }] },
      { n: 4, readingJa: 'よんはい', tokens: [{ b: '四', r: 'よん' }, { b: '杯', r: 'はい' }] },
      { n: 5, readingJa: 'ごはい', tokens: [{ b: '五', r: 'ご' }, { b: '杯', r: 'はい' }] },
      { n: 6, readingJa: 'ろっぱい', tokens: [{ b: '六', r: 'ろっ' }, { b: '杯', r: 'ぱい' }] },
      { n: 7, readingJa: 'ななはい', tokens: [{ b: '七', r: 'なな' }, { b: '杯', r: 'はい' }] },
      { n: 8, readingJa: 'はっぱい', tokens: [{ b: '八', r: 'はっ' }, { b: '杯', r: 'ぱい' }] },
      { n: 9, readingJa: 'きゅうはい', tokens: [{ b: '九', r: 'きゅう' }, { b: '杯', r: 'はい' }] },
      { n: 10, readingJa: 'じゅっぱい', tokens: [{ b: '十', r: 'じゅっ' }, { b: '杯', r: 'ぱい' }] },
    ],
  },
  {
    id: 'dai',
    counter: '台',
    reading: 'だい',
    useKo: '기계 · 차량 · 가전 (자동차 · 컴퓨터 · 냉장고 등)',
    exampleKo: '車(くるま)が二台(にだい) = 차가 두 대.',
    hardKo: '음변화가 없어요. 숫자 읽는 법만 그대로 붙이면 돼요.',
    forms: [
      { n: 1, readingJa: 'いちだい', tokens: [{ b: '一', r: 'いち' }, { b: '台', r: 'だい' }] },
      { n: 2, readingJa: 'にだい', tokens: [{ b: '二', r: 'に' }, { b: '台', r: 'だい' }] },
      { n: 3, readingJa: 'さんだい', tokens: [{ b: '三', r: 'さん' }, { b: '台', r: 'だい' }] },
      { n: 4, readingJa: 'よんだい', tokens: [{ b: '四', r: 'よん' }, { b: '台', r: 'だい' }] },
      { n: 5, readingJa: 'ごだい', tokens: [{ b: '五', r: 'ご' }, { b: '台', r: 'だい' }] },
      { n: 6, readingJa: 'ろくだい', tokens: [{ b: '六', r: 'ろく' }, { b: '台', r: 'だい' }] },
      { n: 7, readingJa: 'ななだい', tokens: [{ b: '七', r: 'なな' }, { b: '台', r: 'だい' }] },
      { n: 8, readingJa: 'はちだい', tokens: [{ b: '八', r: 'はち' }, { b: '台', r: 'だい' }] },
      { n: 9, readingJa: 'きゅうだい', tokens: [{ b: '九', r: 'きゅう' }, { b: '台', r: 'だい' }] },
      { n: 10, readingJa: 'じゅうだい', tokens: [{ b: '十', r: 'じゅう' }, { b: '台', r: 'だい' }] },
    ],
  },
  {
    id: 'kai_times',
    counter: '回',
    reading: 'かい',
    useKo: '횟수 (한 번, 두 번, 세 번)',
    exampleKo: '一日(いちにち)に三回(さんかい) = 하루에 세 번.',
    hardKo: '1(いっかい) · 6(ろっかい) · 8(はっかい) · 10(じゅっかい)에서 촉음이 생겨요.',
    forms: [
      { n: 1, readingJa: 'いっかい', tokens: [{ b: '一', r: 'いっ' }, { b: '回', r: 'かい' }] },
      { n: 2, readingJa: 'にかい', tokens: [{ b: '二', r: 'に' }, { b: '回', r: 'かい' }] },
      { n: 3, readingJa: 'さんかい', tokens: [{ b: '三', r: 'さん' }, { b: '回', r: 'かい' }] },
      { n: 4, readingJa: 'よんかい', tokens: [{ b: '四', r: 'よん' }, { b: '回', r: 'かい' }] },
      { n: 5, readingJa: 'ごかい', tokens: [{ b: '五', r: 'ご' }, { b: '回', r: 'かい' }] },
      { n: 6, readingJa: 'ろっかい', tokens: [{ b: '六', r: 'ろっ' }, { b: '回', r: 'かい' }] },
      { n: 7, readingJa: 'ななかい', tokens: [{ b: '七', r: 'なな' }, { b: '回', r: 'かい' }] },
      { n: 8, readingJa: 'はっかい', tokens: [{ b: '八', r: 'はっ' }, { b: '回', r: 'かい' }] },
      { n: 9, readingJa: 'きゅうかい', tokens: [{ b: '九', r: 'きゅう' }, { b: '回', r: 'かい' }] },
      { n: 10, readingJa: 'じゅっかい', tokens: [{ b: '十', r: 'じゅっ' }, { b: '回', r: 'かい' }] },
    ],
  },
  {
    id: 'sai',
    counter: '歳',
    reading: 'さい',
    useKo: '나이 (몇 살)',
    exampleKo: '私(わたし)は二十歳(はたち)です = 저는 스무 살이에요.',
    hardKo: '1(いっさい) · 8(はっさい) · 10(じゅっさい)은 촉음. 20歳는 특별히 はたち로 읽어요.',
    forms: [
      { n: 1, readingJa: 'いっさい', tokens: [{ b: '一', r: 'いっ' }, { b: '歳', r: 'さい' }] },
      { n: 2, readingJa: 'にさい', tokens: [{ b: '二', r: 'に' }, { b: '歳', r: 'さい' }] },
      { n: 3, readingJa: 'さんさい', tokens: [{ b: '三', r: 'さん' }, { b: '歳', r: 'さい' }] },
      { n: 4, readingJa: 'よんさい', tokens: [{ b: '四', r: 'よん' }, { b: '歳', r: 'さい' }] },
      { n: 5, readingJa: 'ごさい', tokens: [{ b: '五', r: 'ご' }, { b: '歳', r: 'さい' }] },
      { n: 6, readingJa: 'ろくさい', tokens: [{ b: '六', r: 'ろく' }, { b: '歳', r: 'さい' }] },
      { n: 7, readingJa: 'ななさい', tokens: [{ b: '七', r: 'なな' }, { b: '歳', r: 'さい' }] },
      { n: 8, readingJa: 'はっさい', tokens: [{ b: '八', r: 'はっ' }, { b: '歳', r: 'さい' }] },
      { n: 9, readingJa: 'きゅうさい', tokens: [{ b: '九', r: 'きゅう' }, { b: '歳', r: 'さい' }] },
      { n: 10, readingJa: 'じゅっさい', tokens: [{ b: '十', r: 'じゅっ' }, { b: '歳', r: 'さい' }] },
    ],
  },
  {
    id: 'kai_floor',
    counter: '階',
    reading: 'かい',
    useKo: '건물의 층',
    exampleKo: '本屋(ほんや)は三階(さんがい)です = 서점은 3층이에요.',
    hardKo: '3階는 さんがい가 표준(さんかい도 통용). 1いっかい 6ろっかい 10じゅっかい은 촉음.',
    forms: [
      { n: 1, readingJa: 'いっかい', tokens: [{ b: '一', r: 'いっ' }, { b: '階', r: 'かい' }] },
      { n: 2, readingJa: 'にかい', tokens: [{ b: '二', r: 'に' }, { b: '階', r: 'かい' }] },
      { n: 3, readingJa: 'さんがい', tokens: [{ b: '三', r: 'さん' }, { b: '階', r: 'がい' }] },
      { n: 4, readingJa: 'よんかい', tokens: [{ b: '四', r: 'よん' }, { b: '階', r: 'かい' }] },
      { n: 5, readingJa: 'ごかい', tokens: [{ b: '五', r: 'ご' }, { b: '階', r: 'かい' }] },
      { n: 6, readingJa: 'ろっかい', tokens: [{ b: '六', r: 'ろっ' }, { b: '階', r: 'かい' }] },
      { n: 7, readingJa: 'ななかい', tokens: [{ b: '七', r: 'なな' }, { b: '階', r: 'かい' }] },
      { n: 8, readingJa: 'はっかい', tokens: [{ b: '八', r: 'はっ' }, { b: '階', r: 'かい' }] },
      { n: 9, readingJa: 'きゅうかい', tokens: [{ b: '九', r: 'きゅう' }, { b: '階', r: 'かい' }] },
      { n: 10, readingJa: 'じゅっかい', tokens: [{ b: '十', r: 'じゅっ' }, { b: '階', r: 'かい' }] },
    ],
  },
  {
    id: 'en',
    counter: '円',
    reading: 'えん',
    useKo: '일본 돈 (엔)',
    exampleKo: 'これは百円(ひゃくえん)です = 이건 100엔이에요.',
    hardKo: '4円은 よえん(×よんえん)이 자연스러워요. 나머지는 음변화가 없어요.',
    forms: [
      { n: 1, readingJa: 'いちえん', tokens: [{ b: '一', r: 'いち' }, { b: '円', r: 'えん' }] },
      { n: 2, readingJa: 'にえん', tokens: [{ b: '二', r: 'に' }, { b: '円', r: 'えん' }] },
      { n: 3, readingJa: 'さんえん', tokens: [{ b: '三', r: 'さん' }, { b: '円', r: 'えん' }] },
      { n: 4, readingJa: 'よえん', tokens: [{ b: '四', r: 'よ' }, { b: '円', r: 'えん' }] },
      { n: 5, readingJa: 'ごえん', tokens: [{ b: '五', r: 'ご' }, { b: '円', r: 'えん' }] },
      { n: 6, readingJa: 'ろくえん', tokens: [{ b: '六', r: 'ろく' }, { b: '円', r: 'えん' }] },
      { n: 7, readingJa: 'ななえん', tokens: [{ b: '七', r: 'なな' }, { b: '円', r: 'えん' }] },
      { n: 8, readingJa: 'はちえん', tokens: [{ b: '八', r: 'はち' }, { b: '円', r: 'えん' }] },
      { n: 9, readingJa: 'きゅうえん', tokens: [{ b: '九', r: 'きゅう' }, { b: '円', r: 'えん' }] },
      { n: 10, readingJa: 'じゅうえん', tokens: [{ b: '十', r: 'じゅう' }, { b: '円', r: 'えん' }] },
    ],
  },
];

export const COUNTER_TOTAL = COUNTERS.length;
