// 관용구(慣用句) + 사자성어(四字熟語) content. Hand-authored, accurate idioms with
// furigana tokens ({ b, r? }) for FuriganaTokens rendering, full kana reading for
// TTS (expo-speech ja-JP), literal Korean translation vs actual meaning, the
// matching Korean proverb/expression where one exists, and a natural example.
// Static data, no network. Two kinds: 'kanyoku' (관용구) and 'yoji' (사자성어).
export type IdiomKind = 'kanyoku' | 'yoji';

export type Idiom = {
  id: string;
  kind: IdiomKind;
  ja: string; // surface form, e.g. "猫の手も借りたい"
  tokens: { b: string; r?: string }[]; // furigana-annotated surface for FuriganaTokens
  reading: string; // full kana reading, e.g. "ねこのてもかりたい"
  literalKo: string; // 직역 (literal, word-for-word)
  meaningKo: string; // 실제 뜻 (actual idiomatic meaning)
  koEquivalent?: string; // 대응하는 한국 속담/표현
  exampleJa?: string; // natural example sentence in Japanese
  exampleKo?: string; // Korean translation of the example
};

export const IDIOMS: Idiom[] = [
  {
    id: 'neko_no_te',
    kind: 'kanyoku',
    ja: '猫の手も借りたい',
    tokens: [{ b: '猫', r: 'ねこ' }, { b: 'の' }, { b: '手', r: 'て' }, { b: 'も' }, { b: '借', r: 'か' }, { b: 'りたい' }],
    reading: 'ねこのてもかりたい',
    literalKo: '고양이 손이라도 빌리고 싶다',
    meaningKo: '너무 바빠서 누구의 도움이라도 받고 싶을 만큼 일손이 부족하다.',
    koEquivalent: '눈코 뜰 새 없이 바쁘다',
    exampleJa: '年末は猫の手も借りたいほど忙しい。',
    exampleKo: '연말에는 고양이 손이라도 빌리고 싶을 만큼 바쁘다.',
  },
  {
    id: 'hana_yori_dango',
    kind: 'kanyoku',
    ja: '花より団子',
    tokens: [{ b: '花', r: 'はな' }, { b: 'より' }, { b: '団子', r: 'だんご' }],
    reading: 'はなよりだんご',
    literalKo: '꽃보다 경단',
    meaningKo: '풍류나 겉보기보다 실속(먹을 것, 실질적 이득)을 더 챙긴다.',
    koEquivalent: '금강산도 식후경',
    exampleJa: 'お花見と言っても、彼は花より団子だ。',
    exampleKo: '벚꽃놀이라고 해도 그는 꽃보다 경단(먹는 게 우선)이다.',
  },
  {
    id: 'isseki_nicho',
    kind: 'yoji',
    ja: '一石二鳥',
    tokens: [{ b: '一', r: 'いっ' }, { b: '石', r: 'せき' }, { b: '二', r: 'に' }, { b: '鳥', r: 'ちょう' }],
    reading: 'いっせきにちょう',
    literalKo: '돌 하나로 새 두 마리',
    meaningKo: '한 가지 행동으로 두 가지 이득을 동시에 얻는다.',
    koEquivalent: '일석이조 / 꿩 먹고 알 먹고',
    exampleJa: '通勤中に勉強すれば一石二鳥だ。',
    exampleKo: '출근길에 공부하면 일석이조다.',
  },
  {
    id: 'junin_toiro',
    kind: 'yoji',
    ja: '十人十色',
    tokens: [{ b: '十', r: 'じゅう' }, { b: '人', r: 'にん' }, { b: '十', r: 'と' }, { b: '色', r: 'いろ' }],
    reading: 'じゅうにんといろ',
    literalKo: '열 사람이면 열 가지 색',
    meaningKo: '사람마다 생각·취향·성격이 제각각 다르다.',
    koEquivalent: '각인각색 / 사람마다 다르다',
    exampleJa: '好みは十人十色だから、正解はない。',
    exampleKo: '취향은 사람마다 다르니 정답은 없다.',
  },
  {
    id: 'anzuru_umu',
    kind: 'kanyoku',
    ja: '案ずるより産むが易し',
    tokens: [{ b: '案', r: 'あん' }, { b: 'ずるより' }, { b: '産', r: 'う' }, { b: 'むが' }, { b: '易', r: 'やす' }, { b: 'し' }],
    reading: 'あんずるよりうむがやすし',
    literalKo: '걱정하는 것보다 낳는 편이 쉽다',
    meaningKo: '막상 해보면 미리 걱정했던 것보다 훨씬 쉽다.',
    koEquivalent: '걱정도 팔자다 / 막상 해보면 별거 아니다',
    exampleJa: '案ずるより産むが易し、まずやってみよう。',
    exampleKo: '걱정하느니 일단 해보자, 해보면 별거 아니다.',
  },
  {
    id: 'saru_mo_ki',
    kind: 'kanyoku',
    ja: '猿も木から落ちる',
    tokens: [{ b: '猿', r: 'さる' }, { b: 'も' }, { b: '木', r: 'き' }, { b: 'から' }, { b: '落', r: 'お' }, { b: 'ちる' }],
    reading: 'さるもきからおちる',
    literalKo: '원숭이도 나무에서 떨어진다',
    meaningKo: '그 분야의 달인·전문가도 때로는 실수를 한다.',
    koEquivalent: '원숭이도 나무에서 떨어진다',
    exampleJa: '猿も木から落ちる、ベテランでもミスはする。',
    exampleKo: '원숭이도 나무에서 떨어지듯, 베테랑도 실수는 한다.',
  },
  {
    id: 'i_no_naka_kawazu',
    kind: 'kanyoku',
    ja: '井の中の蛙',
    tokens: [{ b: '井', r: 'い' }, { b: 'の' }, { b: '中', r: 'なか' }, { b: 'の' }, { b: '蛙', r: 'かわず' }],
    reading: 'いのなかのかわず',
    literalKo: '우물 안 개구리',
    meaningKo: '좁은 세계만 알고 넓은 세상을 모르는 사람.',
    koEquivalent: '우물 안 개구리',
    exampleJa: '井の中の蛙にならないよう、外の世界を見よう。',
    exampleKo: '우물 안 개구리가 되지 않도록 바깥세상을 보자.',
  },
  {
    id: 'ishi_no_ue',
    kind: 'kanyoku',
    ja: '石の上にも三年',
    tokens: [{ b: '石', r: 'いし' }, { b: 'の' }, { b: '上', r: 'うえ' }, { b: 'にも' }, { b: '三年', r: 'さんねん' }],
    reading: 'いしのうえにもさんねん',
    literalKo: '돌 위에서도 삼 년',
    meaningKo: '차가운 돌도 삼 년 앉으면 따뜻해지듯, 참고 계속하면 반드시 성과가 난다.',
    koEquivalent: '참고 견디면 낙이 온다 / 고진감래',
    exampleJa: '石の上にも三年、続ければ上達するよ。',
    exampleKo: '참고 삼 년, 계속하면 실력이 는다.',
  },
  {
    id: 'hara_ga_tatsu',
    kind: 'kanyoku',
    ja: '腹が立つ',
    tokens: [{ b: '腹', r: 'はら' }, { b: 'が' }, { b: '立', r: 'た' }, { b: 'つ' }],
    reading: 'はらがたつ',
    literalKo: '배가 선다',
    meaningKo: '화가 나다, 부아가 치밀다.',
    koEquivalent: '화가 나다 / 부아가 치밀다',
    exampleJa: '彼の態度に腹が立った。',
    exampleKo: '그의 태도에 화가 났다.',
  },
  {
    id: 'atama_ga_katai',
    kind: 'kanyoku',
    ja: '頭が固い',
    tokens: [{ b: '頭', r: 'あたま' }, { b: 'が' }, { b: '固', r: 'かた' }, { b: 'い' }],
    reading: 'あたまがかたい',
    literalKo: '머리가 딱딱하다',
    meaningKo: '융통성이 없고 고집이 세다, 사고가 완고하다.',
    koEquivalent: '머리가 굳다 / 벽창호',
    exampleJa: '父は頭が固くて新しいやり方を認めない。',
    exampleKo: '아버지는 완고해서 새로운 방식을 인정하지 않는다.',
  },
  {
    id: 'kao_ga_hiroi',
    kind: 'kanyoku',
    ja: '顔が広い',
    tokens: [{ b: '顔', r: 'かお' }, { b: 'が' }, { b: '広', r: 'ひろ' }, { b: 'い' }],
    reading: 'かおがひろい',
    literalKo: '얼굴이 넓다',
    meaningKo: '아는 사람이 많고 인맥이 넓다.',
    koEquivalent: '발이 넓다',
    exampleJa: '彼女は業界で顔が広い。',
    exampleKo: '그녀는 업계에서 발이 넓다.',
  },
  {
    id: 'mimi_ga_itai',
    kind: 'kanyoku',
    ja: '耳が痛い',
    tokens: [{ b: '耳', r: 'みみ' }, { b: 'が' }, { b: '痛', r: 'いた' }, { b: 'い' }],
    reading: 'みみがいたい',
    literalKo: '귀가 아프다',
    meaningKo: '남의 지적·충고가 자기 약점을 찔러 듣기가 괴롭다.',
    koEquivalent: '뜨끔하다 / 귀에 거슬리다(아픈 소리)',
    exampleJa: '節約しろと言われて耳が痛い。',
    exampleKo: '절약하라는 말을 들으니 뜨끔하다.',
  },
  {
    id: 'te_wo_yaku',
    kind: 'kanyoku',
    ja: '手を焼く',
    tokens: [{ b: '手', r: 'て' }, { b: 'を' }, { b: '焼', r: 'や' }, { b: 'く' }],
    reading: 'てをやく',
    literalKo: '손을 굽다(태우다)',
    meaningKo: '다루기 힘들어 애를 먹다, 고생하다.',
    koEquivalent: '애를 먹다 / 골머리를 앓다',
    exampleJa: 'いたずらな弟に手を焼いている。',
    exampleKo: '장난꾸러기 남동생 때문에 애를 먹고 있다.',
  },
  {
    id: 'abura_wo_uru',
    kind: 'kanyoku',
    ja: '油を売る',
    tokens: [{ b: '油', r: 'あぶら' }, { b: 'を' }, { b: '売', r: 'う' }, { b: 'る' }],
    reading: 'あぶらをうる',
    literalKo: '기름을 팔다',
    meaningKo: '일 도중에 잡담이나 딴짓을 하며 시간을 허비하다.',
    koEquivalent: '농땡이 부리다 / 땡땡이치다',
    exampleJa: 'どこで油を売っていたの？',
    exampleKo: '어디서 농땡이 부리다 온 거야?',
  },
  {
    id: 'hana_ga_takai',
    kind: 'kanyoku',
    ja: '鼻が高い',
    tokens: [{ b: '鼻', r: 'はな' }, { b: 'が' }, { b: '高', r: 'たか' }, { b: 'い' }],
    reading: 'はながたかい',
    literalKo: '코가 높다',
    meaningKo: '자랑스럽고 우쭐하다, 뿌듯하다.',
    koEquivalent: '어깨가 으쓱하다 / 콧대가 높다',
    exampleJa: '息子が合格して鼻が高い。',
    exampleKo: '아들이 합격해서 어깨가 으쓱하다.',
  },
  {
    id: 'kubi_wo_nagaku',
    kind: 'kanyoku',
    ja: '首を長くする',
    tokens: [{ b: '首', r: 'くび' }, { b: 'を' }, { b: '長', r: 'なが' }, { b: 'くする' }],
    reading: 'くびをながくする',
    literalKo: '목을 길게 하다',
    meaningKo: '무언가를 몹시 기다리다, 학수고대하다.',
    koEquivalent: '목이 빠지게 기다리다',
    exampleJa: '合格発表を首を長くして待っている。',
    exampleKo: '합격 발표를 목이 빠지게 기다리고 있다.',
  },
  {
    id: 'saba_wo_yomu',
    kind: 'kanyoku',
    ja: 'さばを読む',
    tokens: [{ b: 'さばを' }, { b: '読', r: 'よ' }, { b: 'む' }],
    reading: 'さばをよむ',
    literalKo: '고등어를 세다(읽다)',
    meaningKo: '자기에게 유리하게 수(나이·개수 등)를 속이다.',
    koEquivalent: '나이를 속이다 / 눈속임하다',
    exampleJa: '年齢をさばを読んで若く言った。',
    exampleKo: '나이를 속여서 어리게 말했다.',
  },
  {
    id: 'mizu_ni_nagasu',
    kind: 'kanyoku',
    ja: '水に流す',
    tokens: [{ b: '水', r: 'みず' }, { b: 'に' }, { b: '流', r: 'なが' }, { b: 'す' }],
    reading: 'みずにながす',
    literalKo: '물에 흘려보내다',
    meaningKo: '지난 다툼·원한을 없던 일로 하고 깨끗이 잊다.',
    koEquivalent: '없던 일로 하다 / 물에 흘려보내다',
    exampleJa: '過去のことは水に流そう。',
    exampleKo: '지난 일은 없던 일로 하자.',
  },
  {
    id: 'ki_ga_au',
    kind: 'kanyoku',
    ja: '気が合う',
    tokens: [{ b: '気', r: 'き' }, { b: 'が' }, { b: '合', r: 'あ' }, { b: 'う' }],
    reading: 'きがあう',
    literalKo: '기가 맞다',
    meaningKo: '마음이 잘 맞고 성격이 통하다.',
    koEquivalent: '마음이 잘 맞다 / 코드가 맞다',
    exampleJa: '彼とは初対面から気が合った。',
    exampleKo: '그와는 처음 만났을 때부터 마음이 잘 맞았다.',
  },
  {
    id: 'me_ga_nai',
    kind: 'kanyoku',
    ja: '目がない',
    tokens: [{ b: '目', r: 'め' }, { b: 'が' }, { b: 'ない' }],
    reading: 'めがない',
    literalKo: '눈이 없다',
    meaningKo: '무언가를 몹시 좋아해서 사족을 못 쓰다.',
    koEquivalent: '사족을 못 쓰다 / 환장하다',
    exampleJa: '彼は甘いものに目がない。',
    exampleKo: '그는 단것이라면 사족을 못 쓴다.',
  },
  {
    id: 'ashi_wo_hipparu',
    kind: 'kanyoku',
    ja: '足を引っ張る',
    tokens: [{ b: '足', r: 'あし' }, { b: 'を' }, { b: '引', r: 'ひ' }, { b: 'っ' }, { b: '張', r: 'ぱ' }, { b: 'る' }],
    reading: 'あしをひっぱる',
    literalKo: '발을 잡아당기다',
    meaningKo: '남의 성공·진행을 방해하다, 발목을 잡다.',
    koEquivalent: '발목을 잡다',
    exampleJa: 'チームの足を引っ張りたくない。',
    exampleKo: '팀의 발목을 잡고 싶지 않다.',
  },
  {
    id: 'ne_mimi_ni_mizu',
    kind: 'kanyoku',
    ja: '寝耳に水',
    tokens: [{ b: '寝', r: 'ね' }, { b: '耳', r: 'みみ' }, { b: 'に' }, { b: '水', r: 'みず' }],
    reading: 'ねみみにみず',
    literalKo: '자는 귀에 물',
    meaningKo: '전혀 예상하지 못한 갑작스러운 소식에 깜짝 놀라다.',
    koEquivalent: '아닌 밤중에 홍두깨 / 청천벽력',
    exampleJa: '倒産の話は寝耳に水だった。',
    exampleKo: '도산 소식은 아닌 밤중에 홍두깨였다.',
  },
  {
    id: 'suzume_no_namida',
    kind: 'kanyoku',
    ja: '雀の涙',
    tokens: [{ b: '雀', r: 'すずめ' }, { b: 'の' }, { b: '涙', r: 'なみだ' }],
    reading: 'すずめのなみだ',
    literalKo: '참새의 눈물',
    meaningKo: '아주 적은 양, 쥐꼬리만 한 것.',
    koEquivalent: '쥐꼬리만 하다 / 새 발의 피',
    exampleJa: 'ボーナスは雀の涙ほどだった。',
    exampleKo: '보너스는 쥐꼬리만 했다.',
  },
  {
    id: 'onaji_kama',
    kind: 'kanyoku',
    ja: '同じ釜の飯を食う',
    tokens: [{ b: '同', r: 'おな' }, { b: 'じ' }, { b: '釜', r: 'かま' }, { b: 'の' }, { b: '飯', r: 'めし' }, { b: 'を' }, { b: '食', r: 'く' }, { b: 'う' }],
    reading: 'おなじかまのめしをくう',
    literalKo: '같은 솥의 밥을 먹다',
    meaningKo: '함께 생활하며 고락을 나눈 가까운 사이다.',
    koEquivalent: '한솥밥을 먹다 / 동고동락하다',
    exampleJa: '彼とは同じ釜の飯を食った仲だ。',
    exampleKo: '그와는 한솥밥을 먹은 사이다.',
  },
  {
    id: 'gaden_insui',
    kind: 'yoji',
    ja: '我田引水',
    tokens: [{ b: '我', r: 'が' }, { b: '田', r: 'でん' }, { b: '引', r: 'いん' }, { b: '水', r: 'すい' }],
    reading: 'がでんいんすい',
    literalKo: '내 논에 물 대기',
    meaningKo: '자기에게만 유리하도록 말하거나 행동하다.',
    koEquivalent: '아전인수',
    exampleJa: '彼の説明は我田引水だ。',
    exampleKo: '그의 설명은 아전인수 격이다.',
  },
  {
    id: 'ishin_denshin',
    kind: 'yoji',
    ja: '以心伝心',
    tokens: [{ b: '以', r: 'い' }, { b: '心', r: 'しん' }, { b: '伝', r: 'でん' }, { b: '心', r: 'しん' }],
    reading: 'いしんでんしん',
    literalKo: '마음으로써 마음을 전한다',
    meaningKo: '말하지 않아도 마음이 서로 통하다.',
    koEquivalent: '이심전심 / 척하면 척',
    exampleJa: '長年の夫婦は以心伝心だ。',
    exampleKo: '오랜 부부는 이심전심이다.',
  },
  {
    id: 'yudan_taiteki',
    kind: 'yoji',
    ja: '油断大敵',
    tokens: [{ b: '油', r: 'ゆ' }, { b: '断', r: 'だん' }, { b: '大', r: 'たい' }, { b: '敵', r: 'てき' }],
    reading: 'ゆだんたいてき',
    literalKo: '방심은 큰 적',
    meaningKo: '방심이야말로 실패를 부르는 가장 큰 적이니 늘 조심하라.',
    koEquivalent: '방심은 금물',
    exampleJa: 'リードしていても油断大敵だ。',
    exampleKo: '앞서고 있어도 방심은 금물이다.',
  },
  {
    id: 'jigo_jitoku',
    kind: 'yoji',
    ja: '自業自得',
    tokens: [{ b: '自', r: 'じ' }, { b: '業', r: 'ごう' }, { b: '自', r: 'じ' }, { b: '得', r: 'とく' }],
    reading: 'じごうじとく',
    literalKo: '자기 업(행동)을 자기가 얻다',
    meaningKo: '자기가 저지른 일의 나쁜 결과를 스스로 받다.',
    koEquivalent: '자업자득 / 자기가 뿌린 씨',
    exampleJa: '寝坊して遅刻したのは自業自得だ。',
    exampleKo: '늦잠 자서 지각한 건 자업자득이다.',
  },
  {
    id: 'isshin_furan',
    kind: 'yoji',
    ja: '一心不乱',
    tokens: [{ b: '一', r: 'いっ' }, { b: '心', r: 'しん' }, { b: '不', r: 'ふ' }, { b: '乱', r: 'らん' }],
    reading: 'いっしんふらん',
    literalKo: '한마음으로 흐트러지지 않음',
    meaningKo: '한 가지에 집중하여 다른 데 정신을 팔지 않다.',
    koEquivalent: '일심불란 / 일념으로',
    exampleJa: '一心不乱に絵を描いた。',
    exampleKo: '한마음으로 몰두해 그림을 그렸다.',
  },
  {
    id: 'shiku_hakku',
    kind: 'yoji',
    ja: '四苦八苦',
    tokens: [{ b: '四', r: 'し' }, { b: '苦', r: 'く' }, { b: '八', r: 'はっ' }, { b: '苦', r: 'く' }],
    reading: 'しくはっく',
    literalKo: '네 가지 고통 여덟 가지 고통',
    meaningKo: '온갖 고생을 하며 몹시 애를 먹다.',
    koEquivalent: '갖은 고생 / 진땀을 빼다',
    exampleJa: '引っ越しの準備で四苦八苦した。',
    exampleKo: '이사 준비하느라 갖은 고생을 했다.',
  },
  {
    id: 'ishibashi_wo_tataku',
    kind: 'kanyoku',
    ja: '石橋を叩いて渡る',
    tokens: [{ b: '石橋', r: 'いしばし' }, { b: 'を' }, { b: '叩', r: 'たた' }, { b: 'いて' }, { b: '渡', r: 'わた' }, { b: 'る' }],
    reading: 'いしばしをたたいてわたる',
    literalKo: '돌다리를 두드려 보고 건너다',
    meaningKo: '아주 신중하게 확인에 확인을 거듭하며 조심스럽게 행동하다.',
    koEquivalent: '돌다리도 두들겨 보고 건너라',
    exampleJa: '彼は石橋を叩いて渡る慎重な性格だ。',
    exampleKo: '그는 돌다리도 두들겨 보고 건너는 신중한 성격이다.',
  },
  {
    id: 'nana_korobi',
    kind: 'kanyoku',
    ja: '七転び八起き',
    tokens: [{ b: '七', r: 'なな' }, { b: '転', r: 'ころ' }, { b: 'び' }, { b: '八', r: 'や' }, { b: '起', r: 'お' }, { b: 'き' }],
    reading: 'ななころびやおき',
    literalKo: '일곱 번 넘어지고 여덟 번 일어난다',
    meaningKo: '여러 번 실패해도 굴하지 않고 다시 일어서다.',
    koEquivalent: '칠전팔기 / 오뚝이 정신',
    exampleJa: '七転び八起きの精神で挑戦を続けた。',
    exampleKo: '칠전팔기의 정신으로 도전을 이어갔다.',
  },
  {
    id: 'zen_wa_isoge',
    kind: 'kanyoku',
    ja: '善は急げ',
    tokens: [{ b: '善', r: 'ぜん' }, { b: 'は' }, { b: '急', r: 'いそ' }, { b: 'げ' }],
    reading: 'ぜんはいそげ',
    literalKo: '좋은 일은 서둘러라',
    meaningKo: '좋은 일이라 여겨지면 망설이지 말고 곧바로 실행하라.',
    koEquivalent: '쇠뿔도 단김에 빼라',
    exampleJa: '善は急げ、思い立ったら今日始めよう。',
    exampleKo: '좋은 일은 서둘러라, 마음먹었으면 오늘 시작하자.',
  },
  {
    id: 'chiri_mo_tsumoreba',
    kind: 'kanyoku',
    ja: '塵も積もれば山となる',
    tokens: [{ b: '塵', r: 'ちり' }, { b: 'も' }, { b: '積', r: 'つ' }, { b: 'もれば' }, { b: '山', r: 'やま' }, { b: 'となる' }],
    reading: 'ちりもつもればやまとなる',
    literalKo: '먼지도 쌓이면 산이 된다',
    meaningKo: '아무리 작은 것도 꾸준히 모으면 큰 것이 된다.',
    koEquivalent: '티끌 모아 태산',
    exampleJa: '塵も積もれば山となる、毎日の貯金が大事だ。',
    exampleKo: '티끌 모아 태산, 매일의 저축이 중요하다.',
  },
  {
    id: 'gou_ni_ireba',
    kind: 'kanyoku',
    ja: '郷に入れば郷に従え',
    tokens: [{ b: '郷', r: 'ごう' }, { b: 'に' }, { b: '入', r: 'い' }, { b: 'れば' }, { b: '郷', r: 'ごう' }, { b: 'に' }, { b: '従', r: 'したが' }, { b: 'え' }],
    reading: 'ごうにいればごうにしたがえ',
    literalKo: '고을에 들어가면 그 고을을 따르라',
    meaningKo: '그 지역·집단에 가면 그곳의 관습과 방식에 따라야 한다.',
    koEquivalent: '로마에 가면 로마법을 따르라',
    exampleJa: '郷に入れば郷に従え、現地の習慣を尊重しよう。',
    exampleKo: '로마에 가면 로마법을 따르듯, 현지 관습을 존중하자.',
  },
  {
    id: 'deru_kui',
    kind: 'kanyoku',
    ja: '出る杭は打たれる',
    tokens: [{ b: '出', r: 'で' }, { b: 'る' }, { b: '杭', r: 'くい' }, { b: 'は' }, { b: '打', r: 'う' }, { b: 'たれる' }],
    reading: 'でるくいはうたれる',
    literalKo: '튀어나온 말뚝은 얻어맞는다',
    meaningKo: '재능이나 언동이 두드러지면 남에게 시기·견제를 받는다.',
    koEquivalent: '모난 돌이 정 맞는다',
    exampleJa: '出る杭は打たれるが、実力で示すしかない。',
    exampleKo: '모난 돌이 정 맞지만, 실력으로 보여줄 수밖에 없다.',
  },
  {
    id: 'nodo_kara_te',
    kind: 'kanyoku',
    ja: '喉から手が出る',
    tokens: [{ b: '喉', r: 'のど' }, { b: 'から' }, { b: '手', r: 'て' }, { b: 'が' }, { b: '出', r: 'で' }, { b: 'る' }],
    reading: 'のどからてがでる',
    literalKo: '목구멍에서 손이 나온다',
    meaningKo: '무언가를 몹시 갖고 싶어 참을 수 없다.',
    koEquivalent: '군침이 돌다 / 목이 빠지게 탐나다',
    exampleJa: 'あの新型カメラが喉から手が出るほど欲しい。',
    exampleKo: '저 신형 카메라가 몹시 갖고 싶어 군침이 돈다.',
  },
  {
    id: 'kuchi_ga_karui',
    kind: 'kanyoku',
    ja: '口が軽い',
    tokens: [{ b: '口', r: 'くち' }, { b: 'が' }, { b: '軽', r: 'かる' }, { b: 'い' }],
    reading: 'くちがかるい',
    literalKo: '입이 가볍다',
    meaningKo: '비밀을 지키지 못하고 말을 함부로 옮기다.',
    koEquivalent: '입이 싸다 / 입이 가볍다',
    exampleJa: '彼は口が軽いから秘密は話せない。',
    exampleKo: '그는 입이 싸서 비밀은 말할 수 없다.',
  },
  {
    id: 'hara_wo_waru',
    kind: 'kanyoku',
    ja: '腹を割る',
    tokens: [{ b: '腹', r: 'はら' }, { b: 'を' }, { b: '割', r: 'わ' }, { b: 'る' }],
    reading: 'はらをわる',
    literalKo: '배를 가르다',
    meaningKo: '속마음을 숨김없이 솔직하게 털어놓다.',
    koEquivalent: '속을 터놓다 / 흉금을 털어놓다',
    exampleJa: '一度腹を割って話し合おう。',
    exampleKo: '한번 속을 터놓고 이야기해 보자.',
  },
  {
    id: 'me_kara_uroko',
    kind: 'kanyoku',
    ja: '目から鱗が落ちる',
    tokens: [{ b: '目', r: 'め' }, { b: 'から' }, { b: '鱗', r: 'うろこ' }, { b: 'が' }, { b: '落', r: 'お' }, { b: 'ちる' }],
    reading: 'めからうろこがおちる',
    literalKo: '눈에서 비늘이 떨어지다',
    meaningKo: '어떤 계기로 갑자기 이해가 트여 사물이 훤히 보이다.',
    koEquivalent: '눈이 번쩍 뜨이다 / 깨달음을 얻다',
    exampleJa: '先生の一言で目から鱗が落ちた。',
    exampleKo: '선생님의 한마디에 눈이 번쩍 뜨였다.',
  },
  {
    id: 'neko_ni_koban',
    kind: 'kanyoku',
    ja: '猫に小判',
    tokens: [{ b: '猫', r: 'ねこ' }, { b: 'に' }, { b: '小判', r: 'こばん' }],
    reading: 'ねこにこばん',
    literalKo: '고양이에게 금화',
    meaningKo: '값진 것을 줘도 그 가치를 모르는 사람에게는 소용없다.',
    koEquivalent: '돼지 목에 진주 / 개발에 편자',
    exampleJa: '彼に高級ワインは猫に小判だ。',
    exampleKo: '그에게 고급 와인은 돼지 목에 진주다.',
  },
  {
    id: 'nito_wo_ou',
    kind: 'kanyoku',
    ja: '二兎を追う者は一兎をも得ず',
    tokens: [{ b: '二', r: 'に' }, { b: '兎', r: 'と' }, { b: 'を' }, { b: '追', r: 'お' }, { b: 'う' }, { b: '者', r: 'もの' }, { b: 'は' }, { b: '一', r: 'いっ' }, { b: '兎', r: 'と' }, { b: 'をも' }, { b: '得', r: 'え' }, { b: 'ず' }],
    reading: 'にとをおうものはいっとをもえず',
    literalKo: '두 토끼를 쫓는 자는 한 마리도 잡지 못한다',
    meaningKo: '욕심내어 두 가지를 동시에 노리면 어느 것도 이루지 못한다.',
    koEquivalent: '두 마리 토끼를 잡으려다 다 놓친다',
    exampleJa: '二兎を追う者は一兎をも得ず、一つに集中しなさい。',
    exampleKo: '두 토끼를 쫓다 다 놓치니, 하나에 집중해라.',
  },
  {
    id: 'isogaba_maware',
    kind: 'kanyoku',
    ja: '急がば回れ',
    tokens: [{ b: '急', r: 'いそ' }, { b: 'がば' }, { b: '回', r: 'まわ' }, { b: 'れ' }],
    reading: 'いそがばまわれ',
    literalKo: '급할수록 돌아가라',
    meaningKo: '급할수록 위험한 지름길보다 확실한 길을 택하는 편이 결국 빠르다.',
    koEquivalent: '급할수록 돌아가라',
    exampleJa: '急がば回れ、基礎から丁寧にやろう。',
    exampleKo: '급할수록 돌아가라, 기초부터 차근차근 하자.',
  },
  {
    id: 'te_no_hira',
    kind: 'kanyoku',
    ja: '手のひらを返す',
    tokens: [{ b: '手', r: 'て' }, { b: 'のひらを' }, { b: '返', r: 'かえ' }, { b: 'す' }],
    reading: 'てのひらをかえす',
    literalKo: '손바닥을 뒤집다',
    meaningKo: '태도를 순식간에 정반대로 확 바꾸다.',
    koEquivalent: '손바닥 뒤집듯 하다 / 안면을 바꾸다',
    exampleJa: '成功した途端、彼らは手のひらを返した。',
    exampleKo: '성공하자마자 그들은 손바닥 뒤집듯 태도를 바꿨다.',
  },
  {
    id: 'ichigo_ichie',
    kind: 'yoji',
    ja: '一期一会',
    tokens: [{ b: '一', r: 'いち' }, { b: '期', r: 'ご' }, { b: '一', r: 'いち' }, { b: '会', r: 'え' }],
    reading: 'いちごいちえ',
    literalKo: '평생에 단 한 번의 만남',
    meaningKo: '모든 만남은 일생에 한 번뿐이니 그 순간을 소중히 하라.',
    koEquivalent: '일기일회 / 일생일대의 인연',
    exampleJa: '一期一会の気持ちで人と接する。',
    exampleKo: '일생에 한 번뿐이라는 마음으로 사람을 대한다.',
  },
  {
    id: 'shinki_itten',
    kind: 'yoji',
    ja: '心機一転',
    tokens: [{ b: '心', r: 'しん' }, { b: '機', r: 'き' }, { b: '一', r: 'いっ' }, { b: '転', r: 'てん' }],
    reading: 'しんきいってん',
    literalKo: '마음의 기틀을 한 번 바꾸다',
    meaningKo: '어떤 계기로 마음가짐을 완전히 새롭게 바꾸다.',
    koEquivalent: '심기일전 / 마음을 새로이 하다',
    exampleJa: '転職を機に心機一転頑張る。',
    exampleKo: '이직을 계기로 심기일전하여 열심히 하겠다.',
  },
  {
    id: 'onko_chishin',
    kind: 'yoji',
    ja: '温故知新',
    tokens: [{ b: '温', r: 'おん' }, { b: '故', r: 'こ' }, { b: '知', r: 'ち' }, { b: '新', r: 'しん' }],
    reading: 'おんこちしん',
    literalKo: '옛것을 익혀 새것을 안다',
    meaningKo: '옛 지식·전통을 되새겨 새로운 도리나 지혜를 깨닫다.',
    koEquivalent: '온고지신',
    exampleJa: '温故知新、古典から学ぶことは多い。',
    exampleKo: '온고지신, 고전에서 배울 것이 많다.',
  },
  {
    id: 'kishoutenketsu',
    kind: 'yoji',
    ja: '起承転結',
    tokens: [{ b: '起', r: 'き' }, { b: '承', r: 'しょう' }, { b: '転', r: 'てん' }, { b: '結', r: 'けつ' }],
    reading: 'きしょうてんけつ',
    literalKo: '기승전결',
    meaningKo: '이야기·글을 구성하는 네 단계(발단-전개-전환-결말)의 짜임새.',
    koEquivalent: '기승전결',
    exampleJa: '起承転結のはっきりした文章を書く。',
    exampleKo: '기승전결이 뚜렷한 글을 쓴다.',
  },
  {
    id: 'ryoyaku_kuchi',
    kind: 'kanyoku',
    ja: '良薬は口に苦し',
    tokens: [{ b: '良薬', r: 'りょうやく' }, { b: 'は' }, { b: '口', r: 'くち' }, { b: 'に' }, { b: '苦', r: 'にが' }, { b: 'し' }],
    reading: 'りょうやくはくちににがし',
    literalKo: '좋은 약은 입에 쓰다',
    meaningKo: '진심 어린 충고는 귀에 거슬리지만 자신에게 이롭다.',
    koEquivalent: '좋은 약은 입에 쓰다 / 충언은 귀에 거슬린다',
    exampleJa: '良薬は口に苦し、彼の忠告は正しかった。',
    exampleKo: '좋은 약은 입에 쓰다, 그의 충고는 옳았다.',
  },
  {
    id: 'ame_futte_jikatamaru',
    kind: 'kanyoku',
    ja: '雨降って地固まる',
    tokens: [{ b: '雨', r: 'あめ' }, { b: '降', r: 'ふ' }, { b: 'って' }, { b: '地', r: 'じ' }, { b: '固', r: 'かた' }, { b: 'まる' }],
    reading: 'あめふってじかたまる',
    literalKo: '비 온 뒤에 땅이 굳는다',
    meaningKo: '갈등이나 시련을 겪은 뒤 오히려 관계나 기반이 더 단단해지다.',
    koEquivalent: '비 온 뒤에 땅이 굳는다',
    exampleJa: '喧嘩したけど雨降って地固まる、前より仲良くなった。',
    exampleKo: '싸웠지만 비 온 뒤에 땅이 굳듯 전보다 더 친해졌다.',
  },
];

export const IDIOM_TOTAL = IDIOMS.length;
