// Mixed quick-quiz items for the 오답노트 (Mistakes drill) screen.
// Real N5/N4 content across 어휘 / 문법 / 한자 / 표현.
// promptTokens gives explicit furigana for the Japanese prompt when the sentence
// contains kanji; promptKo is the Korean gloss/question aid.

export type SkillKo = '어휘' | '문법' | '한자' | '표현';

export type MistakeItem = {
  id: string;
  skillKo: SkillKo;
  promptJa: string;
  promptTokens?: { b: string; r?: string }[];
  promptKo?: string;
  choices: string[];
  answerIndex: number;
  explanationKo: string;
};

export const MISTAKE_ITEMS: MistakeItem[] = [
  // ---------- 어휘 (vocabulary) ----------
  {
    id: 'v01',
    skillKo: '어휘',
    promptJa: 'あさ、かおを____。',
    promptTokens: [{ b: '朝', r: 'あさ' }, { b: '、' }, { b: '顔', r: 'かお' }, { b: 'を____。' }],
    promptKo: '아침에 얼굴을 ____.',
    choices: ['あらいます', 'あるきます', 'あそびます', 'あいます'],
    answerIndex: 0,
    explanationKo: '"얼굴을 씻다"는 かおを あらう. あるく=걷다, あそぶ=놀다, あう=만나다.',
  },
  {
    id: 'v02',
    skillKo: '어휘',
    promptJa: 'この みずは とても ____です。',
    promptKo: '이 물은 아주 ____다. (차갑다)',
    choices: ['あつい', 'つめたい', 'あかるい', 'おもい'],
    answerIndex: 1,
    explanationKo: '차가운 물/음료는 つめたい. あつい=뜨겁다, あかるい=밝다, おもい=무겁다.',
  },
  {
    id: 'v03',
    skillKo: '어휘',
    promptJa: 'えきまで バスで ____ぷんです。',
    promptTokens: [{ b: '駅', r: 'えき' }, { b: 'まで バスで ____' }, { b: '分', r: 'ふん' }, { b: 'です。' }],
    promptKo: '역까지 버스로 15분이다.',
    choices: ['じゅうご', 'じゅうこ', 'じゅうよん', 'じゅういち'],
    answerIndex: 0,
    explanationKo: '15는 じゅうご. 5는 ご로 읽어요. 4=よん, 1=いち.',
  },
  {
    id: 'v04',
    skillKo: '어휘',
    promptJa: 'せんせいに しつもんを ____。',
    promptTokens: [{ b: '先生', r: 'せんせい' }, { b: 'に' }, { b: '質問', r: 'しつもん' }, { b: 'を____。' }],
    promptKo: '선생님에게 질문을 ____. (하다)',
    choices: ['します', 'いいます', 'はなします', 'ききます'],
    answerIndex: 0,
    explanationKo: 'しつもんを する가 관용 표현. きく도 "묻다"지만 しつもんを きく는 어색해요.',
  },
  {
    id: 'v05',
    skillKo: '어휘',
    promptJa: '____を きて、そとに でます。',
    promptKo: '____을(를) 입고 밖에 나간다. (코트)',
    choices: ['コート', 'ノート', 'テスト', 'ポスト'],
    answerIndex: 0,
    explanationKo: 'コート=코트. ノート=노트, テスト=시험, ポスト=우체통.',
  },
  {
    id: 'v06',
    skillKo: '어휘',
    promptJa: 'つかれたから、すこし ____たいです。',
    promptKo: '피곤하니까 좀 ____싶다. (쉬다)',
    choices: ['やすみ', 'あそび', 'はたらき', 'いそぎ'],
    answerIndex: 0,
    explanationKo: 'やすむ=쉬다 -> やすみたい. はたらく=일하다, いそぐ=서두르다.',
  },
  {
    id: 'v07',
    skillKo: '어휘',
    promptJa: 'かばんの なかに さいふが ____。',
    promptKo: '가방 안에 지갑이 ____. (있다, 무생물)',
    choices: ['あります', 'います', 'します', 'なります'],
    answerIndex: 0,
    explanationKo: '무생물의 존재는 ある. 사람/동물은 いる. 지갑은 무생물이라 あります.',
  },
  {
    id: 'v08',
    skillKo: '어휘',
    promptJa: 'この もんだいは ____です。かんたんじゃない。',
    promptTokens: [{ b: 'この' }, { b: '問題', r: 'もんだい' }, { b: 'は ____です。かんたんじゃない。' }],
    promptKo: '이 문제는 ____다. 간단하지 않다.',
    choices: ['むずかしい', 'やさしい', 'たのしい', 'うれしい'],
    answerIndex: 0,
    explanationKo: 'かんたん(간단)의 반대는 むずかしい(어렵다). やさしい=쉽다/상냥하다.',
  },

  // ---------- 문법 (grammar) ----------
  {
    id: 'g01',
    skillKo: '문법',
    promptJa: 'わたしは まいにち コーヒー____のみます。',
    promptKo: '나는 매일 커피 ____ 마신다. (목적격 조사)',
    choices: ['を', 'が', 'に', 'で'],
    answerIndex: 0,
    explanationKo: '타동사 のむ의 목적어에는 を. コーヒーを のむ.',
  },
  {
    id: 'g02',
    skillKo: '문법',
    promptJa: 'としょかん____ほんを よみます。',
    promptTokens: [{ b: '図書館', r: 'としょかん' }, { b: '____' }, { b: '本', r: 'ほん' }, { b: 'を よみます。' }],
    promptKo: '도서관____ 책을 읽는다. (장소 조사)',
    choices: ['で', 'に', 'を', 'へ'],
    answerIndex: 0,
    explanationKo: '동작이 일어나는 장소는 で. 존재 장소는 に. 여기선 "읽다"는 동작이라 で.',
  },
  {
    id: 'g03',
    skillKo: '문법',
    promptJa: 'あしたは やすみだから、はやく おきなくても ____。',
    promptKo: '내일은 쉬는 날이니까 일찍 안 일어나도 ____. (괜찮다)',
    choices: ['いいです', 'ください', 'だめです', 'ほしいです'],
    answerIndex: 0,
    explanationKo: '~なくても いい = ~하지 않아도 된다. おきなくても いいです.',
  },
  {
    id: 'g04',
    skillKo: '문법',
    promptJa: 'ごはんを たべた____、はを みがきます。',
    promptTokens: [{ b: 'ごはんを' }, { b: '食', r: 'た' }, { b: 'べた____、' }, { b: '歯', r: 'は' }, { b: 'を みがきます。' }],
    promptKo: '밥을 먹은 ____ 이를 닦는다. (~후에)',
    choices: ['あとで', 'まえに', 'ながら', 'とき'],
    answerIndex: 0,
    explanationKo: 'た형 + あとで = ~한 후에. たべた あとで. まえに는 사전형+まえに.',
  },
  {
    id: 'g05',
    skillKo: '문법',
    promptJa: 'この へやは しずか____、べんきょうしやすい。',
    promptKo: '이 방은 조용____ 공부하기 쉽다. (な형용사 연결)',
    choices: ['で', 'くて', 'て', 'に'],
    answerIndex: 0,
    explanationKo: 'な형용사의 연결형은 で. しずかで. い형용사면 くて를 써요.',
  },
  {
    id: 'g06',
    skillKo: '문법',
    promptJa: 'にほんごが はなせる ____に なりました。',
    promptTokens: [{ b: '日本語', r: 'にほんご' }, { b: 'が はなせる ____に なりました。' }],
    promptKo: '일본어를 말할 수 있게 되었다.',
    choices: ['よう', 'こと', 'もの', 'ところ'],
    answerIndex: 0,
    explanationKo: '~ように なる = ~하게 되다(능력/상태 변화). はなせるように なりました.',
  },
  {
    id: 'g07',
    skillKo: '문법',
    promptJa: 'あめが ____そうですから、かさを もって いきます。',
    promptKo: '비가 올 것 ____ 하니까 우산을 가져간다. (양태 そう)',
    choices: ['ふり', 'ふる', 'ふって', 'ふった'],
    answerIndex: 0,
    explanationKo: '동사 ます형 어간 + そう = ~할 것 같다. ふります -> ふりそう.',
  },
  {
    id: 'g08',
    skillKo: '문법',
    promptJa: 'いもうとは わたし____ せが たかいです。',
    promptTokens: [{ b: '妹', r: 'いもうと' }, { b: 'は わたし____ せが' }, { b: '高', r: 'たか' }, { b: 'いです。' }],
    promptKo: '여동생은 나____ 키가 크다. (~보다)',
    choices: ['より', 'から', 'まで', 'ほど'],
    answerIndex: 0,
    explanationKo: '비교 기준 "~보다"는 より. AはBより = A는 B보다.',
  },
  {
    id: 'g09',
    skillKo: '문법',
    promptJa: 'まどが あいて ____。だれか あけましたか。',
    promptKo: '창문이 열려 ____. 누가 열었나요? (상태 지속)',
    choices: ['います', 'あります', 'おきます', 'みます'],
    answerIndex: 0,
    explanationKo: '자동사 あく + ている = 상태 지속. まどが あいて います(창이 열려 있다).',
  },
  {
    id: 'g10',
    skillKo: '문법',
    promptJa: 'いそがしくて、ひるごはんを たべる ____が なかった。',
    promptTokens: [{ b: 'いそがしくて、' }, { b: '昼', r: 'ひる' }, { b: 'ごはんを たべる ____が なかった。' }],
    promptKo: '바빠서 점심을 먹을 ____이 없었다. (시간)',
    choices: ['じかん', 'ところ', 'つもり', 'よてい'],
    answerIndex: 0,
    explanationKo: '사전형 + じかんが ない = ~할 시간이 없다. たべる じかんが なかった.',
  },

  // ---------- 한자 (kanji reading/meaning) ----------
  {
    id: 'k01',
    skillKo: '한자',
    promptJa: '「今日」の よみかたは?',
    promptKo: '「今日」의 읽는 법은?',
    choices: ['きょう', 'こんにち', 'いまび', 'きんじつ'],
    answerIndex: 0,
    explanationKo: '今日 = きょう(오늘). こんにち는 こんにちは의 인사말에만 쓰는 특수 독음.',
  },
  {
    id: 'k02',
    skillKo: '한자',
    promptJa: '「食べる」の よみかたは?',
    promptKo: '「食べる」의 읽는 법은?',
    choices: ['たべる', 'しょくべる', 'くべる', 'のべる'],
    answerIndex: 0,
    explanationKo: '食べる = たべる(먹다). 음독 しょく는 食堂(しょくどう) 같은 한자어에 쓰여요.',
  },
  {
    id: 'k03',
    skillKo: '한자',
    promptJa: '「時間」の よみかたは?',
    promptKo: '「時間」의 읽는 법은?',
    choices: ['じかん', 'じがん', 'ときま', 'じっかん'],
    answerIndex: 0,
    explanationKo: '時間 = じかん(시간). 時=じ, 間=かん.',
  },
  {
    id: 'k04',
    skillKo: '한자',
    promptJa: '「やすい」を かんじで かくと?',
    promptKo: '「やすい」(싸다)를 한자로 쓰면?',
    choices: ['安い', '高い', '休い', '早い'],
    answerIndex: 0,
    explanationKo: '安い=싸다. 高い=비싸다/높다, 早い=이르다. 休는 やすむ(쉬다).',
  },
  {
    id: 'k05',
    skillKo: '한자',
    promptJa: '「先生」の よみかたは?',
    promptKo: '「先生」의 읽는 법은?',
    choices: ['せんせい', 'せんせえ', 'さきせい', 'せんじょう'],
    answerIndex: 0,
    explanationKo: '先生 = せんせい(선생님). 先=せん, 生=せい.',
  },
  {
    id: 'k06',
    skillKo: '한자',
    promptJa: '「大きい」の よみかたは?',
    promptKo: '「大きい」의 읽는 법은?',
    choices: ['おおきい', 'だいきい', 'たいきい', 'おうきい'],
    answerIndex: 0,
    explanationKo: '大きい = おおきい(크다). 훈독 おお에 주의(おう가 아님).',
  },
  {
    id: 'k07',
    skillKo: '한자',
    promptJa: '「みず」を かんじで かくと?',
    promptKo: '「みず」(물)를 한자로 쓰면?',
    choices: ['水', '氷', '永', '木'],
    answerIndex: 0,
    explanationKo: '水=みず(물). 氷=こおり(얼음), 永=えい(영원), 木=き(나무). 획에 주의.',
  },
  {
    id: 'k08',
    skillKo: '한자',
    promptJa: '「電車」の よみかたは?',
    promptKo: '「電車」의 읽는 법은?',
    choices: ['でんしゃ', 'でんじゃ', 'でんくるま', 'てんしゃ'],
    answerIndex: 0,
    explanationKo: '電車 = でんしゃ(전철). 電=でん, 車=しゃ.',
  },
  {
    id: 'k09',
    skillKo: '한자',
    promptJa: '「かう」(구입)を かんじで かくと?',
    promptKo: '「かう」(사다/구입)를 한자로 쓰면?',
    choices: ['買う', '売う', '会う', '飼う'],
    answerIndex: 0,
    explanationKo: '買う=사다. 売る(うる)=팔다, 会う(あう)=만나다. 買와 売는 헷갈리기 쉬워요.',
  },
  {
    id: 'k10',
    skillKo: '한자',
    promptJa: '「毎朝」の よみかたは?',
    promptKo: '「毎朝」의 읽는 법은?',
    choices: ['まいあさ', 'まいちょう', 'ごとあさ', 'まいゆう'],
    answerIndex: 0,
    explanationKo: '毎朝 = まいあさ(매일 아침). 毎=まい, 朝=あさ. 毎晩은 まいばん(매일 밤).',
  },

  // ---------- 표현 (situational expressions) ----------
  {
    id: 'e01',
    skillKo: '표현',
    promptJa: 'みせに はいる とき、てんいんは なんと いいますか。',
    promptKo: '가게에 들어갈 때 점원이 하는 말은?',
    choices: ['いらっしゃいませ', 'いってきます', 'おかえりなさい', 'ごちそうさま'],
    answerIndex: 0,
    explanationKo: 'いらっしゃいませ=어서 오세요(점원 인사). いってきます=다녀오겠습니다.',
  },
  {
    id: 'e02',
    skillKo: '표현',
    promptJa: 'しょくじの まえに いう ことばは?',
    promptKo: '식사 전에 하는 말은?',
    choices: ['いただきます', 'ごちそうさま', 'おやすみ', 'ただいま'],
    answerIndex: 0,
    explanationKo: '식사 전=いただきます, 식사 후=ごちそうさまでした.',
  },
  {
    id: 'e03',
    skillKo: '표현',
    promptJa: 'ともだちに プレゼントを もらった。なんと いう?',
    promptKo: '친구에게 선물을 받았다. 뭐라고 말할까?',
    choices: ['ありがとう', 'ごめんなさい', 'おめでとう', 'さようなら'],
    answerIndex: 0,
    explanationKo: '감사는 ありがとう. おめでとう=축하해, ごめんなさい=미안해.',
  },
  {
    id: 'e04',
    skillKo: '표현',
    promptJa: 'ひとの あしを ふんで しまった。なんと いう?',
    promptKo: '남의 발을 밟아 버렸다. 뭐라고 말할까?',
    choices: ['すみません', 'おめでとう', 'おつかれさま', 'いただきます'],
    answerIndex: 0,
    explanationKo: '사과할 때는 すみません / ごめんなさい. おつかれさま=수고하셨어요.',
  },
  {
    id: 'e05',
    skillKo: '표현',
    promptJa: 'よる、ねる まえに かぞくに いう ことばは?',
    promptKo: '밤에 자기 전 가족에게 하는 말은?',
    choices: ['おやすみなさい', 'おはようございます', 'こんばんは', 'ただいま'],
    answerIndex: 0,
    explanationKo: '자기 전=おやすみなさい. こんばんは는 저녁 인사(만났을 때).',
  },
  {
    id: 'e06',
    skillKo: '표현',
    promptJa: 'いえに かえった とき、いう ことばは?',
    promptKo: '집에 돌아왔을 때 하는 말은?',
    choices: ['ただいま', 'いってきます', 'おかえり', 'いらっしゃい'],
    answerIndex: 0,
    explanationKo: '돌아온 사람=ただいま, 맞이하는 사람=おかえりなさい.',
  },
  {
    id: 'e07',
    skillKo: '표현',
    promptJa: 'あいての なまえが わからない。ていねいに きくには?',
    promptKo: '상대 이름을 모른다. 공손하게 묻는 표현은?',
    choices: ['おなまえは なんですか', 'なまえは なに', 'だれだ', 'なまえを いえ'],
    answerIndex: 0,
    explanationKo: '공손하게는 おなまえは なんですか. お+명사, ~ですか로 정중하게.',
  },
  {
    id: 'e08',
    skillKo: '표현',
    promptJa: 'かいぎが おわった。どうりょうに かける ことばは?',
    promptKo: '회의가 끝났다. 동료에게 건네는 말은?',
    choices: ['おつかれさまでした', 'いただきます', 'はじめまして', 'ごめんください'],
    answerIndex: 0,
    explanationKo: '일/회의 후=おつかれさまでした. はじめまして=처음 뵙겠습니다.',
  },
];

export const ROUND_SIZE = 10;
