PERSONAS = [
    {
        "id": "yui",
        "displayName": "유이",
        "japaneseName": "ゆい",
        "role": "다정한 일본인 친구",
        "voiceStyle": "밝고 부드러운 20대 여성 보이스",
        "teachingStyle": "초보자 친화, 칭찬 많음, 한국어 설명 40%",
        "avatarEmoji": "🌸",
        "defaultLanguageMix": {"ko": 40, "ja": 60},
    },
    {
        "id": "haruka",
        "displayName": "하루카 센세",
        "japaneseName": "はるか先生",
        "role": "차분한 일본어 선생님",
        "voiceStyle": "차분하고 명료한 선생님 보이스",
        "teachingStyle": "문법, 뉘앙스, JLPT, 발음 교정 중심",
        "avatarEmoji": "📘",
        "defaultLanguageMix": {"ko": 55, "ja": 45},
    },
    {
        "id": "ren",
        "displayName": "렌 선배",
        "japaneseName": "レン先輩",
        "role": "장난기 있는 애니풍 선배",
        "voiceStyle": "청량하고 자신감 있는 남성 보이스",
        "teachingStyle": "애니 말투와 현실 일본어 차이를 재밌게 설명",
        "avatarEmoji": "⚡",
        "defaultLanguageMix": {"ko": 35, "ja": 65},
    },
    {
        "id": "akari",
        "displayName": "아카리",
        "japaneseName": "あかり",
        "role": "오사카 사투리를 살짝 쓰는 활발한 친구",
        "voiceStyle": "밝고 빠른 Kansai-flavored 여성 보이스",
        "teachingStyle": "회화 리듬, 리액션, 친구 말투 중심",
        "avatarEmoji": "🎈",
        "defaultLanguageMix": {"ko": 35, "ja": 65},
    },
    {
        "id": "takeshi",
        "displayName": "타케시",
        "japaneseName": "たけし",
        "role": "저음의 진지한 직장인 선배",
        "voiceStyle": "낮고 안정적인 남성 보이스",
        "teachingStyle": "비즈니스 톤, 짧은 교정, 실전 대화 중심",
        "avatarEmoji": "🧭",
        "defaultLanguageMix": {"ko": 40, "ja": 60},
    },
    {
        "id": "sachiko",
        "displayName": "사치코",
        "japaneseName": "さちこ",
        "role": "따뜻한 동네 할머니 톤의 대화 파트너",
        "voiceStyle": "느긋하고 포근한 고연령 여성 보이스",
        "teachingStyle": "천천히 반복, 생활어휘, 안정감 있는 피드백",
        "avatarEmoji": "🍵",
        "defaultLanguageMix": {"ko": 45, "ja": 55},
    },
    {
        "id": "kota",
        "displayName": "코타",
        "japaneseName": "こうた",
        "role": "초등학생 느낌의 발랄한 말동무",
        "voiceStyle": "높고 또렷한 어린이풍 보이스",
        "teachingStyle": "짧은 문장, 게임식 리액션, 쉬운 반복",
        "avatarEmoji": "🟡",
        "defaultLanguageMix": {"ko": 35, "ja": 65},
    },
    {
        "id": "shiro",
        "displayName": "시로",
        "japaneseName": "シロ",
        "role": "정중한 집사 톤의 롤플레이 파트너",
        "voiceStyle": "차분하고 격식 있는 안내 보이스",
        "teachingStyle": "정중체, 호텔·레스토랑 표현, 매너 뉘앙스 중심",
        "avatarEmoji": "🕯️",
        "defaultLanguageMix": {"ko": 45, "ja": 55},
    },
]

PRACTICE_ROOMS = [
    {
        "id": "tired_today",
        "title": "오늘 너무 피곤했어",
        "primaryPhraseKo": "오늘 너무 피곤했어",
        "primaryPhraseJa": "今日めっちゃ疲れた",
        "alternativePhrasesJa": ["今日はすごく疲れた", "今日ちょっとしんどい"],
        "personaId": "yui",
        "scenario": "친구에게 오늘 힘들었다고 말하기",
        "openingMessage": "오늘은 「今日めっちゃ疲れた」를 실제 친구한테 말하듯 연습해보자.",
        "tags": ["감정표현", "친구말투", "일상"],
    },
    {
        "id": "mental_tired",
        "title": "멘탈 나갔어",
        "primaryPhraseKo": "오늘 멘탈 나갔어",
        "primaryPhraseJa": "今日メンタルやられた",
        "alternativePhrasesJa": ["今日ちょっとしんどい", "もう無理かも"],
        "personaId": "yui",
        "scenario": "일본인 친구에게 힘든 하루 설명하기",
        "openingMessage": "이 표현은 뉘앙스가 중요해. 너무 과하지 않게 말하는 법을 연습하자.",
        "tags": ["감정표현", "현실표현"],
    },
    {
        "id": "cant_go_today",
        "title": "오늘 못 갈 것 같아",
        "primaryPhraseKo": "오늘 못 갈 것 같아",
        "primaryPhraseJa": "今日行けなさそう",
        "alternativePhrasesJa": ["今日はちょっと無理かも", "今日は行けないかもしれない"],
        "personaId": "yui",
        "scenario": "친구와의 약속을 부드럽게 미루기",
        "openingMessage": "거절처럼 들리지 않게, 미안함과 이유를 짧게 붙여보자.",
        "tags": ["약속", "거절", "친구말투"],
    },
    {
        "id": "slept_late",
        "title": "늦잠 잤어",
        "primaryPhraseKo": "오늘 늦잠 잤어",
        "primaryPhraseJa": "今日寝坊しちゃった",
        "alternativePhrasesJa": ["朝寝坊した", "起きるの遅くなっちゃった"],
        "personaId": "yui",
        "scenario": "아침에 늦은 이유 설명하기",
        "openingMessage": "寝坊와 しちゃった를 같이 써서 자연스러운 미안함을 만들어보자.",
        "tags": ["일상", "사과", "친구말투"],
    },
    {
        "id": "work_busy",
        "title": "일이 너무 바빴어",
        "primaryPhraseKo": "오늘 일이 너무 바빴어",
        "primaryPhraseJa": "今日仕事がめっちゃ忙しかった",
        "alternativePhrasesJa": ["今日は仕事でバタバタしてた", "今日仕事がすごく大変だった"],
        "personaId": "haruka",
        "scenario": "퇴근 후 하루 설명하기",
        "openingMessage": "忙しい의 과거형과 バタバタしてた의 생활 표현 차이를 잡아보자.",
        "tags": ["일상", "형용사", "직장"],
    },
    {
        "id": "want_coffee",
        "title": "커피 마시고 싶어",
        "primaryPhraseKo": "커피 마시고 싶어",
        "primaryPhraseJa": "コーヒー飲みたい",
        "alternativePhrasesJa": ["コーヒー飲みに行きたい", "ちょっとコーヒー飲みたいな"],
        "personaId": "yui",
        "scenario": "친구에게 카페 가자고 말하기",
        "openingMessage": "たい형으로 원하는 걸 가볍게 말하고, な로 부드럽게 끝내보자.",
        "tags": ["희망표현", "카페", "친구말투"],
    },
    {
        "id": "what_do_weekend",
        "title": "주말에 뭐 해?",
        "primaryPhraseKo": "주말에 뭐 해?",
        "primaryPhraseJa": "週末何してる？",
        "alternativePhrasesJa": ["週末予定ある？", "週末何するの？"],
        "personaId": "ren",
        "scenario": "가볍게 주말 약속 물어보기",
        "openingMessage": "予定ある？와 何してる？의 거리감 차이를 실제 대화처럼 연습하자.",
        "tags": ["약속", "질문", "친구말투"],
    },
    {
        "id": "sounds_fun",
        "title": "재밌겠다",
        "primaryPhraseKo": "재밌겠다",
        "primaryPhraseJa": "楽しそう",
        "alternativePhrasesJa": ["面白そう", "めっちゃ楽しそう"],
        "personaId": "yui",
        "scenario": "친구의 계획에 리액션하기",
        "openingMessage": "そう를 써서 자연스러운 반응을 짧고 빠르게 말해보자.",
        "tags": ["리액션", "추측", "친구말투"],
    },
    {
        "id": "not_feeling_well",
        "title": "몸이 좀 안 좋아",
        "primaryPhraseKo": "몸이 좀 안 좋아",
        "primaryPhraseJa": "ちょっと体調悪い",
        "alternativePhrasesJa": ["ちょっと具合悪い", "少し体調がよくない"],
        "personaId": "haruka",
        "scenario": "컨디션을 무겁지 않게 설명하기",
        "openingMessage": "体調와 具合의 차이를 잡고, 너무 직접적인 병명 없이 말해보자.",
        "tags": ["컨디션", "감정표현", "일상"],
    },
    {
        "id": "cold_like",
        "title": "감기 기운 있어",
        "primaryPhraseKo": "감기 기운이 있는 것 같아",
        "primaryPhraseJa": "ちょっと風邪っぽい",
        "alternativePhrasesJa": ["風邪ひいたかも", "少し風邪気味かも"],
        "personaId": "haruka",
        "scenario": "아플 것 같을 때 미리 말하기",
        "openingMessage": "っぽい와 かも를 비교하면서 확신 낮은 표현을 연습하자.",
        "tags": ["컨디션", "뉘앙스", "추측"],
    },
    {
        "id": "say_again",
        "title": "다시 말해줄래?",
        "primaryPhraseKo": "다시 말해줄래?",
        "primaryPhraseJa": "もう一回言ってくれる？",
        "alternativePhrasesJa": ["もう一度言ってもらえる？", "もう一回お願い"],
        "personaId": "yui",
        "scenario": "못 들었을 때 자연스럽게 다시 요청하기",
        "openingMessage": "くれる？와 もらえる？의 부드러움을 비교해보자.",
        "tags": ["듣기", "요청", "친구말투"],
    },
    {
        "id": "speak_slowly",
        "title": "천천히 말해줘",
        "primaryPhraseKo": "천천히 말해줘",
        "primaryPhraseJa": "ゆっくり話して",
        "alternativePhrasesJa": ["もう少しゆっくり話してくれる？", "ゆっくり言ってもらえる？"],
        "personaId": "haruka",
        "scenario": "상대 말이 빠를 때 요청하기",
        "openingMessage": "명령처럼 들리지 않게 くれる？를 붙이는 연습을 하자.",
        "tags": ["듣기", "요청", "발음연습"],
    },
    {
        "id": "dont_understand",
        "title": "잘 모르겠어",
        "primaryPhraseKo": "잘 모르겠어",
        "primaryPhraseJa": "よくわからない",
        "alternativePhrasesJa": ["ちょっとわからない", "まだよくわかってない"],
        "personaId": "haruka",
        "scenario": "이해하지 못했을 때 솔직하게 말하기",
        "openingMessage": "わからない를 너무 세게 말하지 않고, ちょっと로 완충해보자.",
        "tags": ["학습표현", "요청", "뉘앙스"],
    },
    {
        "id": "one_more_time_try",
        "title": "한 번 더 해볼게",
        "primaryPhraseKo": "한 번 더 해볼게",
        "primaryPhraseJa": "もう一回やってみる",
        "alternativePhrasesJa": ["もう一回言ってみる", "もう一度試してみる"],
        "personaId": "haruka",
        "scenario": "발음이나 문장을 다시 시도하기",
        "openingMessage": "てみる로 시도 느낌을 만들고, 自信 없어도 계속 이어가보자.",
        "tags": ["발음연습", "시도", "학습표현"],
    },
    {
        "id": "thanks_for_waiting",
        "title": "기다려줘서 고마워",
        "primaryPhraseKo": "기다려줘서 고마워",
        "primaryPhraseJa": "待ってくれてありがとう",
        "alternativePhrasesJa": ["待っててくれてありがとう", "待たせてごめんね"],
        "personaId": "yui",
        "scenario": "늦었을 때 고마움과 미안함 말하기",
        "openingMessage": "ありがとう와 ごめんね를 상황에 맞게 섞는 연습을 하자.",
        "tags": ["감사", "사과", "친구말투"],
    },
    {
        "id": "sorry_late_reply",
        "title": "답장 늦어서 미안",
        "primaryPhraseKo": "답장 늦어서 미안",
        "primaryPhraseJa": "返信遅くなってごめん",
        "alternativePhrasesJa": ["返事遅れてごめん", "返信遅くなっちゃってごめん"],
        "personaId": "yui",
        "scenario": "메시지 답장이 늦었을 때",
        "openingMessage": "遅い가 아니라 遅くなる로 상황 변화를 표현해보자.",
        "tags": ["사과", "메시지", "친구말투"],
    },
    {
        "id": "can_i_ask",
        "title": "하나 물어봐도 돼?",
        "primaryPhraseKo": "하나 물어봐도 돼?",
        "primaryPhraseJa": "一つ聞いてもいい？",
        "alternativePhrasesJa": ["ちょっと聞いてもいい？", "質問してもいい？"],
        "personaId": "ren",
        "scenario": "대화 중 질문을 꺼내기",
        "openingMessage": "てもいい？로 허락을 구하는 자연스러운 시작을 연습하자.",
        "tags": ["질문", "허락", "친구말투"],
    },
    {
        "id": "that_helped",
        "title": "도움 됐어",
        "primaryPhraseKo": "도움 됐어",
        "primaryPhraseJa": "助かった",
        "alternativePhrasesJa": ["本当に助かった", "ありがとう、助かったよ"],
        "personaId": "ren",
        "scenario": "상대가 도와준 뒤 짧게 고마움 표현하기",
        "openingMessage": "役に立った보다 실제 대화에서 자주 쓰는 助かった를 연습하자.",
        "tags": ["감사", "리액션", "일상"],
    },
    {
        "id": "lets_decide_later",
        "title": "나중에 정하자",
        "primaryPhraseKo": "나중에 정하자",
        "primaryPhraseJa": "あとで決めよう",
        "alternativePhrasesJa": ["またあとで決めよう", "あとで相談しよう"],
        "personaId": "yui",
        "scenario": "일정을 바로 정하지 않고 미루기",
        "openingMessage": "決める와 相談する를 상황에 맞게 바꿔 말해보자.",
        "tags": ["약속", "제안", "친구말투"],
    },
    {
        "id": "not_like_that",
        "title": "그런 뜻은 아니야",
        "primaryPhraseKo": "그런 뜻은 아니야",
        "primaryPhraseJa": "そういう意味じゃない",
        "alternativePhrasesJa": ["そういうつもりじゃない", "悪い意味じゃないよ"],
        "personaId": "haruka",
        "scenario": "오해를 부드럽게 풀기",
        "openingMessage": "意味와 つもり의 차이를 잡고, 방어적으로 들리지 않게 말해보자.",
        "tags": ["뉘앙스", "오해", "친구말투"],
    },
    {
        "id": "formal_cannot_today",
        "title": "오늘은 대응하기 어렵습니다",
        "primaryPhraseKo": "오늘은 대응하기 어렵습니다",
        "primaryPhraseJa": "本日は対応しかねます",
        "alternativePhrasesJa": ["本日は対応が難しいです", "本日中の対応は難しいです"],
        "personaId": "haruka",
        "scenario": "업무 상황에서 정중하게 어렵다고 말하기",
        "openingMessage": "できません보다 부드럽고 격식 있는 しかねます를 연습하자.",
        "tags": ["격식", "직장", "거절"],
    },
    {
        "id": "shadowing_short",
        "title": "짧게 따라 말하기",
        "primaryPhraseKo": "듣고 따라 해볼게",
        "primaryPhraseJa": "聞いて真似してみる",
        "alternativePhrasesJa": ["聞きながら言ってみる", "もう一回真似してみる"],
        "personaId": "haruka",
        "scenario": "쉐도잉 루틴 시작하기",
        "openingMessage": "聞きながら와 真似してみる를 묶어서 말하기 루틴을 만들어보자.",
        "tags": ["쉐도잉", "발음연습", "듣기"],
    },
]

TRAVEL_PRACTICE_ROOMS = [
    {
        "id": "airport_arrival",
        "title": "공항에 도착했어요",
        "primaryPhraseKo": "공항에 도착했어요",
        "primaryPhraseJa": "空港に着きました",
        "alternativePhrasesJa": ["今空港に着きました", "空港に到着しました"],
        "personaId": "haruka",
        "scenario": "일본 공항 도착 후 위치 알리기",
        "openingMessage": "着く와 到着する의 자연스러운 차이를 잡고, 도착 보고를 짧게 해보자.",
        "tags": ["여행", "공항", "보고"],
    },
    {
        "id": "immigration_purpose",
        "title": "관광하러 왔어요",
        "primaryPhraseKo": "관광하러 왔어요",
        "primaryPhraseJa": "観光で来ました",
        "alternativePhrasesJa": ["旅行で来ました", "観光目的です"],
        "personaId": "haruka",
        "scenario": "입국 심사에서 방문 목적 말하기",
        "openingMessage": "목적을 길게 설명하지 않고 안전하게 짧은 문장으로 말해보자.",
        "tags": ["여행", "공항", "격식"],
    },
    {
        "id": "lost_luggage",
        "title": "짐이 안 보여요",
        "primaryPhraseKo": "짐이 안 보여요",
        "primaryPhraseJa": "荷物が見つかりません",
        "alternativePhrasesJa": ["スーツケースが見つかりません", "荷物が出てきません"],
        "personaId": "haruka",
        "scenario": "수하물이 나오지 않을 때 직원에게 말하기",
        "openingMessage": "ない보다 見つかりません으로 차분하게 문제를 설명해보자.",
        "tags": ["여행", "공항", "문제해결"],
    },
    {
        "id": "train_ticket",
        "title": "신주쿠까지 표 주세요",
        "primaryPhraseKo": "신주쿠까지 표 주세요",
        "primaryPhraseJa": "新宿までの切符をください",
        "alternativePhrasesJa": ["新宿までお願いします", "新宿行きの切符をください"],
        "personaId": "yui",
        "scenario": "역에서 목적지까지 표 사기",
        "openingMessage": "まで와 行き의 차이를 잡고, 역무원에게 짧게 요청해보자.",
        "tags": ["여행", "교통", "요청"],
    },
    {
        "id": "which_platform",
        "title": "몇 번 플랫폼이에요?",
        "primaryPhraseKo": "몇 번 플랫폼이에요?",
        "primaryPhraseJa": "何番ホームですか",
        "alternativePhrasesJa": ["どのホームですか", "何番線ですか"],
        "personaId": "yui",
        "scenario": "기차 타는 곳 물어보기",
        "openingMessage": "ホーム와 番線을 같이 익혀서 역 안에서 바로 물어보자.",
        "tags": ["여행", "교통", "질문"],
    },
    {
        "id": "missed_train",
        "title": "전철을 놓쳤어요",
        "primaryPhraseKo": "전철을 놓쳤어요",
        "primaryPhraseJa": "電車に乗り遅れました",
        "alternativePhrasesJa": ["電車を逃しました", "乗る電車を間違えました"],
        "personaId": "haruka",
        "scenario": "이동 중 문제가 생겼을 때 설명하기",
        "openingMessage": "乗り遅れる와 逃す를 비교하며 실제 이동 문제를 말해보자.",
        "tags": ["여행", "교통", "문제해결"],
    },
    {
        "id": "hotel_checkin",
        "title": "예약했어요",
        "primaryPhraseKo": "예약했어요",
        "primaryPhraseJa": "予約しています",
        "alternativePhrasesJa": ["予約があります", "チェックインお願いします"],
        "personaId": "haruka",
        "scenario": "호텔 체크인하기",
        "openingMessage": "予約しています 한 문장으로 체크인을 자연스럽게 시작해보자.",
        "tags": ["여행", "호텔", "격식"],
    },
    {
        "id": "luggage_drop",
        "title": "짐 맡겨도 돼요?",
        "primaryPhraseKo": "짐 맡겨도 돼요?",
        "primaryPhraseJa": "荷物を預けてもいいですか",
        "alternativePhrasesJa": ["荷物を預かってもらえますか", "チェックイン前に荷物を預けたいです"],
        "personaId": "haruka",
        "scenario": "체크인 전 짐 맡기기",
        "openingMessage": "預ける와 預かる의 시점을 구분해 요청해보자.",
        "tags": ["여행", "호텔", "요청"],
    },
    {
        "id": "room_problem",
        "title": "에어컨이 안 돼요",
        "primaryPhraseKo": "방 에어컨이 안 돼요",
        "primaryPhraseJa": "部屋のエアコンが動きません",
        "alternativePhrasesJa": ["エアコンがつきません", "部屋のエアコンを見てもらえますか"],
        "personaId": "haruka",
        "scenario": "객실 문제를 프런트에 말하기",
        "openingMessage": "動きません으로 기계가 작동하지 않는 상황을 차분히 말해보자.",
        "tags": ["여행", "호텔", "문제해결"],
    },
    {
        "id": "late_checkout",
        "title": "체크아웃 늦출 수 있나요?",
        "primaryPhraseKo": "체크아웃을 늦출 수 있나요?",
        "primaryPhraseJa": "チェックアウトを延ばせますか",
        "alternativePhrasesJa": ["レイトチェックアウトできますか", "チェックアウト時間を延長できますか"],
        "personaId": "haruka",
        "scenario": "호텔에서 체크아웃 시간 연장 요청하기",
        "openingMessage": "延ばす와 延長する를 상황에 맞게 써보자.",
        "tags": ["여행", "호텔", "요청"],
    },
    {
        "id": "wifi_password",
        "title": "와이파이 비밀번호 알려주세요",
        "primaryPhraseKo": "와이파이 비밀번호 알려주세요",
        "primaryPhraseJa": "Wi-Fiのパスワードを教えてください",
        "alternativePhrasesJa": ["Wi-Fiは使えますか", "パスワードはどこにありますか"],
        "personaId": "yui",
        "scenario": "숙소나 카페에서 와이파이 묻기",
        "openingMessage": "教えてください를 요청 말투로 자연스럽게 써보자.",
        "tags": ["여행", "호텔", "요청"],
    },
    {
        "id": "charger_borrow",
        "title": "충전기 빌릴 수 있나요?",
        "primaryPhraseKo": "충전기 빌릴 수 있나요?",
        "primaryPhraseJa": "充電器を借りられますか",
        "alternativePhrasesJa": ["充電器を貸してもらえますか", "スマホを充電できますか"],
        "personaId": "yui",
        "scenario": "충전이 필요할 때 도움 요청하기",
        "openingMessage": "借りる와 貸す의 방향을 헷갈리지 않게 연습해보자.",
        "tags": ["여행", "요청", "문제해결"],
    },
    {
        "id": "order_ramen",
        "title": "라멘 하나 주세요",
        "primaryPhraseKo": "쇼유 라멘 하나 주세요",
        "primaryPhraseJa": "醤油ラーメンを一つください",
        "alternativePhrasesJa": ["醤油ラーメンお願いします", "これを一つください"],
        "personaId": "ren",
        "scenario": "식당에서 메뉴 주문하기",
        "openingMessage": "一つください와 お願いします로 안전하게 주문해보자.",
        "tags": ["여행", "식당", "요청"],
    },
    {
        "id": "no_wasabi",
        "title": "와사비 빼주세요",
        "primaryPhraseKo": "와사비 빼주세요",
        "primaryPhraseJa": "わさび抜きでお願いします",
        "alternativePhrasesJa": ["わさびなしでお願いします", "わさびは入れないでください"],
        "personaId": "ren",
        "scenario": "원하지 않는 재료 빼달라고 하기",
        "openingMessage": "抜き와 なし를 비교하며 주문 옵션을 자연스럽게 말해보자.",
        "tags": ["여행", "식당", "요청"],
    },
    {
        "id": "allergy_notice",
        "title": "알레르기가 있어요",
        "primaryPhraseKo": "알레르기가 있어요",
        "primaryPhraseJa": "アレルギーがあります",
        "alternativePhrasesJa": ["卵アレルギーがあります", "これは何が入っていますか"],
        "personaId": "haruka",
        "scenario": "음식 알레르기 말하기",
        "openingMessage": "안전 관련 표현은 짧고 정확하게 말하는 연습을 하자.",
        "tags": ["여행", "식당", "안전"],
    },
    {
        "id": "split_bill",
        "title": "따로 계산할 수 있나요?",
        "primaryPhraseKo": "따로 계산할 수 있나요?",
        "primaryPhraseJa": "別々に払えますか",
        "alternativePhrasesJa": ["会計を別々にできますか", "別会計でお願いします"],
        "personaId": "yui",
        "scenario": "식당에서 더치페이 요청하기",
        "openingMessage": "別々와 別会計를 식당 상황에서 연습해보자.",
        "tags": ["여행", "식당", "결제"],
    },
    {
        "id": "table_for_two",
        "title": "두 명이에요",
        "primaryPhraseKo": "두 명이에요",
        "primaryPhraseJa": "二人です",
        "alternativePhrasesJa": ["二名です", "二人で予約しています"],
        "personaId": "ren",
        "scenario": "식당 입장 시 인원 말하기",
        "openingMessage": "二人와 二名의 캐주얼/격식 차이를 잡아보자.",
        "tags": ["여행", "식당", "격식"],
    },
    {
        "id": "make_reservation",
        "title": "예약할 수 있나요?",
        "primaryPhraseKo": "예약할 수 있나요?",
        "primaryPhraseJa": "予約できますか",
        "alternativePhrasesJa": ["今夜予約できますか", "二人で予約したいです"],
        "personaId": "haruka",
        "scenario": "식당 예약 문의하기",
        "openingMessage": "できますか와 したいです를 섞어 예약 의도를 말해보자.",
        "tags": ["여행", "식당", "예약"],
    },
    {
        "id": "convenience_bag",
        "title": "봉투 하나 주세요",
        "primaryPhraseKo": "봉투 하나 주세요",
        "primaryPhraseJa": "袋を一枚ください",
        "alternativePhrasesJa": ["袋お願いします", "レジ袋をください"],
        "personaId": "yui",
        "scenario": "편의점에서 봉투 요청하기",
        "openingMessage": "枚를 써서 봉투를 세는 표현을 연습하자.",
        "tags": ["여행", "쇼핑", "요청"],
    },
    {
        "id": "card_ok",
        "title": "카드 되나요?",
        "primaryPhraseKo": "카드 되나요?",
        "primaryPhraseJa": "カードは使えますか",
        "alternativePhrasesJa": ["クレジットカードは使えますか", "現金だけですか"],
        "personaId": "yui",
        "scenario": "결제 수단 물어보기",
        "openingMessage": "使える를 결제 상황에서 바로 쓸 수 있게 연습해보자.",
        "tags": ["여행", "쇼핑", "결제"],
    },
    {
        "id": "tax_free",
        "title": "면세 되나요?",
        "primaryPhraseKo": "면세 되나요?",
        "primaryPhraseJa": "免税できますか",
        "alternativePhrasesJa": ["免税の手続きはできますか", "パスポートが必要ですか"],
        "personaId": "haruka",
        "scenario": "쇼핑 중 면세 문의하기",
        "openingMessage": "免税와 手続き를 묶어 매장에서 문의해보자.",
        "tags": ["여행", "쇼핑", "격식"],
    },
    {
        "id": "try_on",
        "title": "입어봐도 돼요?",
        "primaryPhraseKo": "입어봐도 돼요?",
        "primaryPhraseJa": "試着してもいいですか",
        "alternativePhrasesJa": ["これ試着できますか", "試着室はどこですか"],
        "personaId": "yui",
        "scenario": "옷가게에서 착용 문의하기",
        "openingMessage": "試着してもいいですか를 부드럽게 말해보자.",
        "tags": ["여행", "쇼핑", "허락"],
    },
    {
        "id": "ask_direction",
        "title": "역이 어느 쪽이에요?",
        "primaryPhraseKo": "역이 어느 쪽이에요?",
        "primaryPhraseJa": "駅はどっちですか",
        "alternativePhrasesJa": ["駅はどちらですか", "駅までどう行けばいいですか"],
        "personaId": "yui",
        "scenario": "길을 물어보기",
        "openingMessage": "どっち와 どちら의 거리감 차이를 연습해보자.",
        "tags": ["여행", "길찾기", "질문"],
    },
    {
        "id": "lost_way",
        "title": "길을 잃었어요",
        "primaryPhraseKo": "길을 잃었어요",
        "primaryPhraseJa": "道に迷いました",
        "alternativePhrasesJa": ["ちょっと迷っています", "ここがどこかわかりません"],
        "personaId": "haruka",
        "scenario": "길을 잃었을 때 도움 요청하기",
        "openingMessage": "迷いました로 상황을 정확히 말하고 다음 도움을 요청해보자.",
        "tags": ["여행", "길찾기", "문제해결"],
    },
    {
        "id": "restroom_where",
        "title": "화장실 어디예요?",
        "primaryPhraseKo": "화장실 어디예요?",
        "primaryPhraseJa": "トイレはどこですか",
        "alternativePhrasesJa": ["お手洗いはどこですか", "トイレを探しています"],
        "personaId": "yui",
        "scenario": "공공장소에서 화장실 묻기",
        "openingMessage": "トイレ와 お手洗い의 캐주얼/정중 차이를 익혀보자.",
        "tags": ["여행", "길찾기", "질문"],
    },
    {
        "id": "take_photo",
        "title": "사진 찍어주실 수 있나요?",
        "primaryPhraseKo": "사진 찍어주실 수 있나요?",
        "primaryPhraseJa": "写真を撮ってもらえますか",
        "alternativePhrasesJa": ["写真をお願いできますか", "一枚撮ってもらえますか"],
        "personaId": "yui",
        "scenario": "관광지에서 사진 부탁하기",
        "openingMessage": "撮ってもらえますか로 낯선 사람에게 정중하게 부탁해보자.",
        "tags": ["여행", "요청", "관광"],
    },
    {
        "id": "clinic_need",
        "title": "병원에 가고 싶어요",
        "primaryPhraseKo": "병원에 가고 싶어요",
        "primaryPhraseJa": "病院に行きたいです",
        "alternativePhrasesJa": ["病院を探しています", "近くの病院はありますか"],
        "personaId": "haruka",
        "scenario": "몸이 아파 병원 도움 요청하기",
        "openingMessage": "안전 상황에서는 짧고 분명한 문장으로 도움을 요청해보자.",
        "tags": ["여행", "안전", "컨디션"],
    },
    {
        "id": "medicine_have",
        "title": "두통약 있나요?",
        "primaryPhraseKo": "두통약 있나요?",
        "primaryPhraseJa": "頭痛薬はありますか",
        "alternativePhrasesJa": ["痛み止めはありますか", "薬局はどこですか"],
        "personaId": "haruka",
        "scenario": "약국에서 증상 관련 약 찾기",
        "openingMessage": "頭痛薬와 痛み止め를 구분해 말해보자.",
        "tags": ["여행", "안전", "컨디션"],
    },
    {
        "id": "emergency_help",
        "title": "도와주세요",
        "primaryPhraseKo": "도와주세요",
        "primaryPhraseJa": "助けてください",
        "alternativePhrasesJa": ["助けが必要です", "救急車を呼んでください"],
        "personaId": "haruka",
        "scenario": "긴급 상황에서 도움 요청하기",
        "openingMessage": "긴급 표현은 변형보다 즉시 말할 수 있는 기본형을 먼저 익히자.",
        "tags": ["여행", "안전", "긴급"],
    },
    {
        "id": "police_lost",
        "title": "지갑을 잃어버렸어요",
        "primaryPhraseKo": "지갑을 잃어버렸어요",
        "primaryPhraseJa": "財布をなくしました",
        "alternativePhrasesJa": ["財布を落としました", "交番はどこですか"],
        "personaId": "haruka",
        "scenario": "분실 상황을 설명하고 파출소 찾기",
        "openingMessage": "なくす와 落とす의 차이를 잡고 차분히 신고 표현을 연습하자.",
        "tags": ["여행", "안전", "문제해결"],
    },
]

PRACTICE_ROOMS.extend(TRAVEL_PRACTICE_ROOMS)

COURSE_CATALOG = [
    {
        "id": "jp_beginner_speaking_ko",
        "title": "Korean-first Japanese Speaking Foundations",
        "targetLanguage": "ja",
        "nativeLanguage": "ko",
        "level": "beginner_to_low_intermediate",
        "descriptionKo": "한국어 사고에서 바로 일본어 일상 대화로 넘어가기 위한 첫 코스",
        "units": [
            {
                "id": "unit_daily_feelings",
                "title": "하루 컨디션과 감정 말하기",
                "order": 1,
                "skillTags": ["감정표현", "컨디션", "친구말투"],
                "lessons": [
                    {
                        "id": "lesson_tired_feelings",
                        "title": "피곤함과 멘탈 표현",
                        "order": 1,
                        "practiceRoomIds": ["tired_today", "mental_tired"],
                    },
                    {
                        "id": "lesson_body_condition",
                        "title": "몸 상태 가볍게 설명하기",
                        "order": 2,
                        "practiceRoomIds": ["not_feeling_well", "cold_like"],
                    },
                ],
            },
            {
                "id": "unit_everyday_plans",
                "title": "약속과 가벼운 제안",
                "order": 2,
                "skillTags": ["약속", "제안", "거절"],
                "lessons": [
                    {
                        "id": "lesson_cancel_or_delay",
                        "title": "못 가거나 나중에 정하기",
                        "order": 1,
                        "practiceRoomIds": ["cant_go_today", "lets_decide_later"],
                    },
                    {
                        "id": "lesson_weekend_and_cafe",
                        "title": "주말과 카페 제안",
                        "order": 2,
                        "practiceRoomIds": ["what_do_weekend", "want_coffee"],
                    },
                ],
            },
            {
                "id": "unit_listening_repair",
                "title": "못 들었을 때 다시 이어가기",
                "order": 3,
                "skillTags": ["듣기", "요청", "발음연습"],
                "lessons": [
                    {
                        "id": "lesson_repeat_requests",
                        "title": "다시 말해달라고 하기",
                        "order": 1,
                        "practiceRoomIds": ["say_again", "speak_slowly", "dont_understand"],
                    },
                    {
                        "id": "lesson_try_shadowing",
                        "title": "다시 말하고 따라 하기",
                        "order": 2,
                        "practiceRoomIds": ["one_more_time_try", "shadowing_short"],
                    },
                ],
            },
            {
                "id": "unit_social_messages",
                "title": "메시지와 짧은 리액션",
                "order": 4,
                "skillTags": ["메시지", "리액션", "감사"],
                "lessons": [
                    {
                        "id": "lesson_apology_messages",
                        "title": "늦음과 답장 사과",
                        "order": 1,
                        "practiceRoomIds": ["slept_late", "sorry_late_reply", "thanks_for_waiting"],
                    },
                    {
                        "id": "lesson_reaction_question",
                        "title": "질문하고 반응하기",
                        "order": 2,
                        "practiceRoomIds": ["can_i_ask", "that_helped", "sounds_fun"],
                    },
                ],
            },
            {
                "id": "unit_nuance_and_work",
                "title": "오해, 직장, 격식 표현",
                "order": 5,
                "skillTags": ["뉘앙스", "직장", "격식"],
                "lessons": [
                    {
                        "id": "lesson_workday_nuance",
                        "title": "바쁜 하루와 오해 풀기",
                        "order": 1,
                        "practiceRoomIds": ["work_busy", "not_like_that"],
                    },
                    {
                        "id": "lesson_formal_refusal",
                        "title": "정중하게 어렵다고 말하기",
                        "order": 2,
                        "practiceRoomIds": ["formal_cannot_today"],
                    },
                ],
            },
        ],
    },
    {
        "id": "jp_travel_survival_ko",
        "title": "Korean-first Japanese Travel Survival",
        "targetLanguage": "ja",
        "nativeLanguage": "ko",
        "level": "beginner_travel",
        "descriptionKo": "일본 여행과 체류 중 바로 쓰는 공항, 교통, 호텔, 식당, 안전 표현 코스",
        "units": [
            {
                "id": "unit_travel_arrival",
                "title": "공항과 이동 시작",
                "order": 1,
                "skillTags": ["여행", "공항", "교통"],
                "lessons": [
                    {
                        "id": "lesson_airport_entry",
                        "title": "공항 도착과 입국",
                        "order": 1,
                        "practiceRoomIds": ["airport_arrival", "immigration_purpose", "lost_luggage"],
                    },
                    {
                        "id": "lesson_train_start",
                        "title": "전철 타기와 플랫폼 찾기",
                        "order": 2,
                        "practiceRoomIds": ["train_ticket", "which_platform", "missed_train"],
                    },
                ],
            },
            {
                "id": "unit_hotel_stay",
                "title": "호텔 체크인과 체류",
                "order": 2,
                "skillTags": ["호텔", "요청", "문제해결"],
                "lessons": [
                    {
                        "id": "lesson_checkin_luggage",
                        "title": "체크인과 짐 맡기기",
                        "order": 1,
                        "practiceRoomIds": ["hotel_checkin", "luggage_drop", "room_problem"],
                    },
                    {
                        "id": "lesson_hotel_requests",
                        "title": "체류 중 요청",
                        "order": 2,
                        "practiceRoomIds": ["late_checkout", "wifi_password", "charger_borrow"],
                    },
                ],
            },
            {
                "id": "unit_food_ordering",
                "title": "식당 주문과 결제",
                "order": 3,
                "skillTags": ["식당", "요청", "결제"],
                "lessons": [
                    {
                        "id": "lesson_order_options",
                        "title": "주문과 재료 요청",
                        "order": 1,
                        "practiceRoomIds": ["order_ramen", "no_wasabi", "allergy_notice"],
                    },
                    {
                        "id": "lesson_table_payment",
                        "title": "인원, 예약, 계산",
                        "order": 2,
                        "practiceRoomIds": ["table_for_two", "make_reservation", "split_bill"],
                    },
                ],
            },
            {
                "id": "unit_shopping_city",
                "title": "쇼핑과 길찾기",
                "order": 4,
                "skillTags": ["쇼핑", "길찾기", "질문"],
                "lessons": [
                    {
                        "id": "lesson_payment_shopping",
                        "title": "쇼핑 결제와 면세",
                        "order": 1,
                        "practiceRoomIds": ["convenience_bag", "card_ok", "tax_free", "try_on"],
                    },
                    {
                        "id": "lesson_directions_city",
                        "title": "길 묻기와 길 잃기",
                        "order": 2,
                        "practiceRoomIds": ["ask_direction", "lost_way", "restroom_where", "take_photo"],
                    },
                ],
            },
            {
                "id": "unit_safety_help",
                "title": "건강과 긴급 상황",
                "order": 5,
                "skillTags": ["안전", "컨디션", "문제해결"],
                "lessons": [
                    {
                        "id": "lesson_clinic_pharmacy",
                        "title": "병원과 약국",
                        "order": 1,
                        "practiceRoomIds": ["clinic_need", "medicine_have"],
                    },
                    {
                        "id": "lesson_emergency_lost",
                        "title": "긴급 도움과 분실",
                        "order": 2,
                        "practiceRoomIds": ["emergency_help", "police_lost"],
                    },
                ],
            },
        ],
    },
]


def _apply_course_metadata() -> None:
    index = {}
    for course in COURSE_CATALOG:
        for unit in course["units"]:
            for lesson in unit["lessons"]:
                for room_order, room_id in enumerate(lesson["practiceRoomIds"], start=1):
                    index[room_id] = {
                        "courseId": course["id"],
                        "courseTitle": course["title"],
                        "unitId": unit["id"],
                        "unitTitle": unit["title"],
                        "unitOrder": unit["order"],
                        "lessonId": lesson["id"],
                        "lessonTitle": lesson["title"],
                        "lessonOrder": lesson["order"],
                        "roomOrder": room_order,
                    }
    for room in PRACTICE_ROOMS:
        room.update(index.get(room["id"], {}))


_apply_course_metadata()

JLPT_GRAMMAR_POINTS = [
    {
        "id": "grammar_n5_ta_past",
        "level": "N5",
        "title": "た形 / 과거형",
        "pattern": "Vた",
        "meaningKo": "이미 한 일이나 상태를 말할 때 쓰는 과거형",
        "exampleJa": "今日は疲れた。",
        "exampleKo": "오늘은 피곤했어.",
        "commonKoreanMistake": "疲れるだった처럼 사전형에 だった를 붙이는 실수",
        "tags": ["동사시제", "감정표현", "tired_today"],
    },
    {
        "id": "grammar_n5_sugoku_meccha",
        "level": "N5",
        "title": "すごく / めっちゃ 정도 부사",
        "pattern": "すごく + 형용사 / めっちゃ + 형용사",
        "meaningKo": "엄청, 너무, 진짜 같은 강한 정도 표현",
        "exampleJa": "今日めっちゃ疲れた。",
        "exampleKo": "오늘 진짜 피곤했어.",
        "commonKoreanMistake": "너무를 항상 とても로만 옮겨서 친구 말투가 딱딱해지는 실수",
        "tags": ["친구말투", "감정표현", "자연스러움"],
    },
    {
        "id": "grammar_n4_sou",
        "level": "N4",
        "title": "そう / ~할 것 같아",
        "pattern": "Vます stem + そう",
        "meaningKo": "겉보기나 상황상 그렇게 될 것 같다는 말",
        "exampleJa": "今日行けなさそう。",
        "exampleKo": "오늘 못 갈 것 같아.",
        "commonKoreanMistake": "같아를 모두 みたい로만 옮기는 실수",
        "tags": ["약속", "추측", "친구말투"],
    },
    {
        "id": "grammar_n3_yarareta",
        "level": "N3",
        "title": "やられた / 당했다, 멘탈이 나갔다",
        "pattern": "N/상황 + にやられた",
        "meaningKo": "무언가에 타격을 받거나 지쳤다는 캐주얼 표현",
        "exampleJa": "今日メンタルやられた。",
        "exampleKo": "오늘 멘탈 나갔어.",
        "commonKoreanMistake": "멘탈을 그대로 メンタル가 아니라 문맥 없이 心라고 옮겨 어색해지는 실수",
        "tags": ["감정표현", "현실표현", "멘탈"],
    },
    {
        "id": "grammar_n4_teiru_state",
        "level": "N4",
        "title": "ている / 상태와 진행",
        "pattern": "Vている",
        "meaningKo": "지금 진행 중인 동작이나 결과 상태를 말할 때 쓰는 표현",
        "exampleJa": "今日はちょっと疲れている。",
        "exampleKo": "오늘은 조금 피곤한 상태야.",
        "commonKoreanMistake": "피곤해 있다를 疲れてある처럼 직역하는 실수",
        "tags": ["상태표현", "감정표현", "동사시제"],
    },
    {
        "id": "grammar_n4_kamo",
        "level": "N4",
        "title": "かも / ~일지도, ~일 수도",
        "pattern": "普通形 + かも",
        "meaningKo": "확신은 약하지만 가능성을 말하는 캐주얼 표현",
        "exampleJa": "今日はちょっと無理かも。",
        "exampleKo": "오늘은 좀 무리일지도.",
        "commonKoreanMistake": "모든 '같아'를 と思う로만 말해서 뉘앙스가 무거워지는 실수",
        "tags": ["추측", "친구말투", "약속"],
    },
    {
        "id": "grammar_n3_wakejanai",
        "level": "N3",
        "title": "わけじゃない / 꼭 ~라는 건 아니다",
        "pattern": "普通形 + わけじゃない",
        "meaningKo": "오해를 부드럽게 줄이며 전면 부정은 아닌 뉘앙스",
        "exampleJa": "行きたくないわけじゃないけど、今日は疲れてる。",
        "exampleKo": "가기 싫다는 건 아닌데, 오늘은 피곤해.",
        "commonKoreanMistake": "아닌데를 じゃないだけ로 직역해 어색해지는 실수",
        "tags": ["뉘앙스", "거절", "감정표현"],
    },
    {
        "id": "grammar_n2_kara_toitte",
        "level": "N2",
        "title": "からといって / ~라고 해서",
        "pattern": "普通形 + からといって",
        "meaningKo": "어떤 이유가 바로 결론으로 이어지지는 않음을 말함",
        "exampleJa": "疲れているからといって、全部断るわけじゃない。",
        "exampleKo": "피곤하다고 해서 전부 거절하는 건 아니야.",
        "commonKoreanMistake": "라고 해서를 と言って만 반복해 문장이 딱딱해지는 실수",
        "tags": ["논리연결", "뉘앙스", "N2"],
    },
    {
        "id": "grammar_n5_i_adjective",
        "level": "N5",
        "title": "い형용사 과거 / ~했다",
        "pattern": "Aい -> Aかった",
        "meaningKo": "い형용사의 과거 상태를 말할 때 쓰는 기본 활용",
        "exampleJa": "今日は忙しかった。",
        "exampleKo": "오늘은 바빴어.",
        "commonKoreanMistake": "忙しいだった처럼 い형용사에 だった를 붙이는 실수",
        "tags": ["형용사", "동사시제", "일상"],
    },
    {
        "id": "grammar_n5_na_adjective",
        "level": "N5",
        "title": "な형용사 과거 / ~했다",
        "pattern": "Aな -> Aだった",
        "meaningKo": "な형용사의 과거 상태를 말할 때 쓰는 활용",
        "exampleJa": "今日は大変だった。",
        "exampleKo": "오늘은 힘들었어.",
        "commonKoreanMistake": "大変かった처럼 な형용사를 い형용사처럼 활용하는 실수",
        "tags": ["형용사", "감정표현", "일상"],
    },
    {
        "id": "grammar_n4_te_miru",
        "level": "N4",
        "title": "てみる / 한번 ~해보다",
        "pattern": "Vて + みる",
        "meaningKo": "시도나 가벼운 제안을 말할 때 쓰는 표현",
        "exampleJa": "もう一回言ってみる。",
        "exampleKo": "한 번 더 말해볼게.",
        "commonKoreanMistake": "해보다를 見る로만 직역해 실제 시도 뉘앙스가 사라지는 실수",
        "tags": ["발음연습", "시도", "친구말투"],
    },
    {
        "id": "grammar_n4_nagara",
        "level": "N4",
        "title": "ながら / ~하면서",
        "pattern": "Vます stem + ながら",
        "meaningKo": "두 행동을 동시에 할 때 쓰는 표현",
        "exampleJa": "聞きながら真似してみて。",
        "exampleKo": "들으면서 따라 해봐.",
        "commonKoreanMistake": "하면서를 しながらだけ로 뭉뚱그려 동사 연결을 놓치는 실수",
        "tags": ["쉐도잉", "발음연습", "듣기"],
    },
    {
        "id": "grammar_n3_te_shimau",
        "level": "N3",
        "title": "てしまう / 해버리다",
        "pattern": "Vて + しまう",
        "meaningKo": "아쉬움, 완료, 의도치 않은 결과를 말할 때 쓰는 표현",
        "exampleJa": "今日は寝落ちしてしまった。",
        "exampleKo": "오늘은 깜빡 잠들어버렸어.",
        "commonKoreanMistake": "버리다를 捨てる로 직역하는 실수",
        "tags": ["감정표현", "일상", "뉘앙스"],
    },
    {
        "id": "grammar_n3_ppoi",
        "level": "N3",
        "title": "っぽい / ~스러운, ~같은",
        "pattern": "N/A stem + っぽい",
        "meaningKo": "느낌이나 경향을 캐주얼하게 말할 때 쓰는 표현",
        "exampleJa": "ちょっと風邪っぽい。",
        "exampleKo": "약간 감기 기운이 있는 것 같아.",
        "commonKoreanMistake": "같아를 모두 みたい로만 말해 뉘앙스가 단조로워지는 실수",
        "tags": ["컨디션", "친구말투", "뉘앙스"],
    },
    {
        "id": "grammar_n2_wari_ni",
        "level": "N2",
        "title": "わりに / ~치고는",
        "pattern": "普通形 + わりに",
        "meaningKo": "예상과 다른 정도를 비교할 때 쓰는 표현",
        "exampleJa": "寝てないわりに元気だね。",
        "exampleKo": "잠 못 잔 것치고는 멀쩡하네.",
        "commonKoreanMistake": "치고는을 に比べて만 반복해 어색해지는 실수",
        "tags": ["비교", "컨디션", "N2"],
    },
    {
        "id": "grammar_n2_kaneru",
        "level": "N2",
        "title": "かねる / ~하기 어렵다",
        "pattern": "Vます stem + かねる",
        "meaningKo": "정중하게 어렵거나 불가능함을 말하는 표현",
        "exampleJa": "今日は対応しかねます。",
        "exampleKo": "오늘은 대응하기 어렵습니다.",
        "commonKoreanMistake": "못해요를 전부 できません으로만 처리해 격식 뉘앙스가 부족한 실수",
        "tags": ["격식", "거절", "N2"],
    },
]

KOREAN_MISTAKE_PATTERNS = [
    {
        "id": "km_verb_past_tired",
        "category": "verb_tense",
        "trigger": "疲れるだった",
        "wrongJa": "今日は疲れるだった",
        "betterJa": "今日は疲れた",
        "explanationKo": "사전형 疲れる에 だった를 붙이지 말고 과거형 疲れた를 써야 자연스러워요.",
        "tags": ["동사시제", "감정표현"],
    },
    {
        "id": "km_too_literal_very",
        "category": "naturalness",
        "trigger": "너무",
        "wrongJa": "今日はとても疲れた",
        "betterJa": "今日めっちゃ疲れた",
        "explanationKo": "친구 말투에서는 とても보다 めっちゃ가 더 살아있는 표현이에요. 단, 격식 있는 자리에서는 すごく가 안전합니다.",
        "tags": ["친구말투", "자연스러움"],
    },
    {
        "id": "km_omae_register",
        "category": "register",
        "trigger": "お前",
        "wrongJa": "お前、誰？",
        "betterJa": "え、誰？ / どちら様ですか？",
        "explanationKo": "お前는 애니에서는 자주 보여도 현실에서는 거칠게 들릴 수 있어요. 상황에 맞춰 부드럽게 바꾸는 게 좋아요.",
        "tags": ["애니vs현실", "말투"],
    },
    {
        "id": "km_mental_literal",
        "category": "loanword_nuance",
        "trigger": "멘탈",
        "wrongJa": "心が出た",
        "betterJa": "メンタルやられた",
        "explanationKo": "한국어 '멘탈 나갔어'는 心가 나갔다는 식으로 직역하지 말고 メンタルやられた처럼 관용적으로 잡는 게 자연스러워요.",
        "tags": ["감정표현", "현실표현"],
    },
    {
        "id": "km_plan_cancel_softness",
        "category": "politeness",
        "trigger": "못 갈 것 같아",
        "wrongJa": "今日は行かないと思う",
        "betterJa": "今日はちょっと行けないかも",
        "explanationKo": "약속 취소는 行かない보다 行けないかも가 덜 차갑고 부드러워요.",
        "tags": ["약속", "거절", "친구말투"],
    },
    {
        "id": "km_i_adjective_past",
        "category": "adjective_tense",
        "trigger": "忙しいだった",
        "wrongJa": "今日は忙しいだった",
        "betterJa": "今日は忙しかった",
        "explanationKo": "い형용사의 과거형은 かった를 붙여요. 忙しいだった는 한국어식 직역처럼 들립니다.",
        "tags": ["형용사", "동사시제", "일상"],
    },
    {
        "id": "km_na_adjective_past",
        "category": "adjective_tense",
        "trigger": "大変かった",
        "wrongJa": "今日は大変かった",
        "betterJa": "今日は大変だった",
        "explanationKo": "大変은 な형용사라 과거형은 大変だった가 자연스러워요.",
        "tags": ["형용사", "감정표현"],
    },
    {
        "id": "km_try_miru_literal",
        "category": "verb_pattern",
        "trigger": "見てみる",
        "wrongJa": "日本語を言って見る",
        "betterJa": "日本語で言ってみる",
        "explanationKo": "시도 의미의 '~해보다'는 보통 てみる로 붙여 쓰고, 실제로 본다는 見る와 구분해야 해요.",
        "tags": ["발음연습", "시도"],
    },
    {
        "id": "km_sleep_fall_literal",
        "category": "naturalness",
        "trigger": "잠이 떨어졌다",
        "wrongJa": "眠りが落ちた",
        "betterJa": "寝落ちした",
        "explanationKo": "한국어식으로 '잠이 떨어졌다'를 직역하지 말고, 깜빡 잠든 상황은 寝落ちした가 자연스러워요.",
        "tags": ["일상", "현실표현"],
    },
    {
        "id": "km_condition_cold_like",
        "category": "nuance",
        "trigger": "감기 같아",
        "wrongJa": "風邪みたい",
        "betterJa": "風邪っぽい",
        "explanationKo": "몸 상태가 감기 기운처럼 느껴질 때는 風邪っぽい가 더 일상적이고 가볍게 들립니다.",
        "tags": ["컨디션", "친구말투"],
    },
    {
        "id": "km_formal_cannot",
        "category": "register",
        "trigger": "못 합니다",
        "wrongJa": "できません",
        "betterJa": "対応しかねます",
        "explanationKo": "업무나 공손한 거절에서는 できません만 반복하기보다 しかねます가 더 격식 있는 선택지예요.",
        "tags": ["격식", "거절"],
    },
    {
        "id": "km_because_direct",
        "category": "logic",
        "trigger": "피곤해서 무조건",
        "wrongJa": "疲れたから絶対できない",
        "betterJa": "疲れているからといって、全部無理なわけじゃない",
        "explanationKo": "이유와 결론을 너무 세게 연결하면 단정적으로 들릴 수 있어요. からといって로 완충할 수 있습니다.",
        "tags": ["논리연결", "뉘앙스"],
    },
    {
        "id": "km_while_shadowing",
        "category": "listening_speaking",
        "trigger": "들으면서 따라",
        "wrongJa": "聞くして真似して",
        "betterJa": "聞きながら真似して",
        "explanationKo": "~하면서는 동사의 ます형 어간에 ながら를 붙여 연결해요.",
        "tags": ["쉐도잉", "듣기", "발음연습"],
    },
]
